<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Multiple Linear Regression – POL232 R Handbook (W2025)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./linreg_inf.html" rel="next">
<link href="./simp_linreg.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./multi_linreg.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">POL232 R Handbook (W2025)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Setting Up R &amp; RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Use of RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./des1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive Statistics (1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./des2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Descriptive Statistics (2)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bivariate Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simp_linreg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multi_linreg.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linreg_inf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistical Inference for Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subsig.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Substantive Significance</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><span class="header-section-number">7.1</span> Overview</a></li>
  <li><a href="#sec-lr-multi" id="toc-sec-lr-multi" class="nav-link" data-scroll-target="#sec-lr-multi"><span class="header-section-number">7.2</span> Linear Regression for Multivariate Analysis</a>
  <ul class="collapse">
  <li><a href="#prepare-variables" id="toc-prepare-variables" class="nav-link" data-scroll-target="#prepare-variables"><span class="header-section-number">7.2.1</span> Prepare Variables</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">7.2.2</span> Multiple Linear Regression</a></li>
  </ul></li>
  <li><a href="#sec-dum-ocat-ind" id="toc-sec-dum-ocat-ind" class="nav-link" data-scroll-target="#sec-dum-ocat-ind"><span class="header-section-number">7.3</span> Dummifying Ordinal Categorical Independent Variable</a>
  <ul class="collapse">
  <li><a href="#sec-dum-ind-fit" id="toc-sec-dum-ind-fit" class="nav-link" data-scroll-target="#sec-dum-ind-fit"><span class="header-section-number">7.3.1</span> Fitted Values from the Linear Regression with Dummified Variables from Categorical Independent Variable</a></li>
  <li><a href="#sec-dum-ind-interpret" id="toc-sec-dum-ind-interpret" class="nav-link" data-scroll-target="#sec-dum-ind-interpret"><span class="header-section-number">7.3.2</span> How to Interpret the Linear Regression Coefficients on Dummified Variables from Categorical Independent Variable</a></li>
  <li><a href="#with-additional-independent-variables" id="toc-with-additional-independent-variables" class="nav-link" data-scroll-target="#with-additional-independent-variables"><span class="header-section-number">7.3.3</span> With Additional Independent Variables</a></li>
  <li><a href="#difference-from-numerical-version" id="toc-difference-from-numerical-version" class="nav-link" data-scroll-target="#difference-from-numerical-version"><span class="header-section-number">7.3.4</span> Difference from Numerical Version</a></li>
  </ul></li>
  <li><a href="#sec-dum-ncat-ind-q" id="toc-sec-dum-ncat-ind-q" class="nav-link" data-scroll-target="#sec-dum-ncat-ind-q"><span class="header-section-number">7.4</span> Dummifying Nominal Categorical Independent Variable: Questions</a></li>
  <li><a href="#sec-dum-ncat-ind-a" id="toc-sec-dum-ncat-ind-a" class="nav-link" data-scroll-target="#sec-dum-ncat-ind-a"><span class="header-section-number">7.5</span> Dummifying Nominal Categorical Independent Variable: Answers</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Before you start</strong> working on this chapter, you need to do the following. If you need a help for each step, see <a href="des1.html#sec-preparation" class="quarto-xref"><span>Section 3.1</span></a>.</p>
<ul>
<li><p>Launch <strong>RStudio</strong>.</p></li>
<li><p>Load <code>POL232.RData</code> into your current <strong>R</strong> session.</p></li>
<li><p>Prepare an <strong>R Script</strong> to save all your work in this chapter. I suggest you name it “<code>POL232_Week#_YourLastName.R</code>” or “<code>POL232_Tutorial#_YourLastName.R</code>” in which <code>#</code> is the number of the current week or tutorial session.</p></li>
<li><p>You also need to load <code>tidyverse</code> package into your current <strong>R</strong> session (<a href="setup.html#sec-load-packages" class="quarto-xref"><span>Section 1.4.2</span></a>).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>I suggest you <span class="red-text">actually write</span> <strong>the R functions</strong> used below in your <strong>R script</strong> instead of copying and pasting them. See <a href="des1.html#sec-actually-write-rscript" class="quarto-xref"><span>Section 3.1.5</span></a> for <span class="red-text">why</span>.</p></li>
<li><p>I also suggest you <span class="red-text">sufficiently annotate</span> your <strong>R script</strong> (i.e.&nbsp;leaving notes after the <code>#</code> sign) so that you can use your <strong>R script</strong> as your reference when you work on tutorial exercises or data analysis paper assignments. In other words, this <strong>R script</strong> will be <span class="red-text">your notes for this chapter</span>.</p></li>
</ul>
<section id="overview" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="overview"><span class="header-section-number">7.1</span> Overview</h2>
<p>While we have started learning statistical inference in lectures, in this chapter, we will still consider <span class="red-text">a linear regression model</span> as <span class="red-text">the method for</span> <strong>descriptive statistics</strong> <span class="red-text">only</span>. We will cover statistical inference for linear regression in later chapters.</p>
<p>This chapter will introduce i) how to fit <span class="red-text">a multiple linear regression model</span> with two or more independent variables on the right-hand side of the linear regression equation, and ii) <span class="red-text">dummification of</span> <strong>a categorical independent variable</strong> in <span class="red-text">a linear regression model</span>.</p>
<p>Note that <span class="red-text">we did not cover</span> the second topic — <span class="red-text">dummification of</span> <strong>a categorical independent variable</strong> — <span class="red-text">in lectures</span>. I want you to learn this topic from this chapter. If you need an additional reference for this topic, you may read <strong>Kellstedt and Whitten’s Chapter 11.2.2 (3rd Edition, pp.251-254) or Chapter 10.2.2 (2nd Edition, pp.225-227)</strong>. Recall that <span class="red-text">the 2nd edition of this book is available online from the UofT library</span>.</p>
</section>
<section id="sec-lr-multi" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="sec-lr-multi"><span class="header-section-number">7.2</span> Linear Regression for Multivariate Analysis</h2>
<section id="prepare-variables" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="prepare-variables"><span class="header-section-number">7.2.1</span> Prepare Variables</h3>
<p>As in <a href="simp_linreg.html" class="quarto-xref"><span>Chapter 6</span></a>, let’s create <code>percep_economy_cps_n</code>, which is <strong>a <code>numeric</code> version</strong> of <code>percep_economy_cps</code>, and <code>union_d</code>, <strong>a <code>logical</code> version</strong> of <code>union</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> ces2019 <span class="sc">|&gt;</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">percep_economy_cps =</span> <span class="fu">fct_relevel</span>(percep_economy_cps, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>              <span class="st">"(2) Worse"</span>, <span class="st">"(3) About the same"</span>, <span class="st">"(1) Better"</span>) ) <span class="sc">|&gt;</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">percep_economy_cps =</span> <span class="fu">fct_recode</span>(percep_economy_cps, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Worse"</span> <span class="ot">=</span> <span class="st">"(2) Worse"</span>, </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Same"</span> <span class="ot">=</span> <span class="st">"(3) About the same"</span>, </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Better"</span> <span class="ot">=</span> <span class="st">"(1) Better"</span>) ) <span class="sc">|&gt;</span> </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">percep_economy_cps_n =</span> <span class="fu">as.numeric</span>(percep_economy_cps))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span>  ces2019 <span class="sc">|&gt;</span> <span class="co"># Change the name of categories of union to TRUE and FALSE.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>( <span class="at">union_d =</span> <span class="fu">fct_recode</span>(union, <span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"(1) Yes"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"(2) No"</span>) ) <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>( <span class="at">union_d =</span> <span class="fu">as.logical</span>(union_d) )  <span class="co"># Then, apply the as.logical() function.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="multiple-linear-regression" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="multiple-linear-regression"><span class="header-section-number">7.2.2</span> Multiple Linear Regression</h3>
<p>Recall that we used <strong>the <code>lm()</code> function</strong> to fit <span class="red-text">a simple linear regression model</span>. For example, the code below fits a simple linear regression model of <code>trudeau_therm_cps</code> on <code>percep_economy_cps_n</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> percep_economy_cps_n, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps_n, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n  
               8.128                18.982  </code></pre>
</div>
</div>
<p>To fit <span class="red-text">a multiple linear regression model</span>, we continue to use <strong>the <code>lm()</code> function</strong>, but now we need to specify <span class="red-text">multiple independent variables</span> on <strong>the right hand side</strong> of the equation in <strong>the <code>formula</code> argument</strong>. More specifically, suppose that the model we try to fit is given by the following formula in which we have three independent variables, <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, and <span class="math inline">\(X_3\)</span>.</p>
<p><span id="eq-lm2"><span class="math display">\[
  Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + u
\tag{7.1}\]</span></span></p>
<p>For this model, we specify <strong>the <code>formula</code> argument</strong> in <strong>the <code>lm</code> function</strong> as <strong><code>formula = Y ~ X1 + X2 + X3</code></strong>. That is, ignoring the coefficients, we <span class="red-text">connect all the independent variables with a <code>+</code> sign</span> on <strong>the right-hand side of tilde, <code>~</code></strong>.</p>
<p>Let’s fit <span class="red-text">a multiple linear regression model</span> of <code>trudeau_therm_cps</code> on three independent variables, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code>, where <code>percep_economy_cps_n</code> corresponds to <span class="math inline">\(X_1\)</span>, <code>ideology</code> corresponds to <span class="math inline">\(X_2\)</span>, and <code>union_d</code> corresponds to <span class="math inline">\(X_3\)</span> in <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;<span>7.1</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> percep_economy_cps_n <span class="sc">+</span> ideology <span class="sc">+</span> union_d, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps_n + ideology + 
    union_d, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n              ideology  
             24.7569               17.1926               -2.7193  
         union_dTRUE  
              0.8752  </code></pre>
</div>
</div>
<p>As before, we can see <span class="red-text">the list of coefficients</span> computed at the bottom of the output. <strong>The number below <code>(Intercept)</code></strong> is <span class="red-text">the intercept</span> of the linear regression model. This is an estimate of <span class="math inline">\(\beta_0\)</span> in the linear regression model in <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;<span>7.1</span></a>. <strong>The number below <code>percep_economy_cps_n</code></strong> is <span class="red-text">the coefficient of the <code>percep_economy_cps_n</code> variable</span>, which corresponds to <span class="math inline">\(\beta_1\)</span> in the linear regression model in <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;<span>7.1</span></a>. <strong>The number below <code>ideology</code></strong> is <span class="red-text">the coefficient of the <code>ideology</code> variable</span>, which is an estimate of <span class="math inline">\(\beta_2\)</span> in <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;<span>7.1</span></a>. Finally, <strong>the number below <code>union_dTRUE</code></strong> is <span class="red-text">the coefficient of the <code>union_d</code> variable</span>, which is an estimate of <span class="math inline">\(\beta_3\)</span> in <a href="#eq-lm2" class="quarto-xref">Equation&nbsp;<span>7.1</span></a>.</p>
<p>If we have more independent variables than what is shown in this example, we can simply <span class="red-text">add them</span> on <strong>the right hand side of the tilde <code>~</code></strong> in <strong>the <code>formula</code> argument</strong> <span class="red-text">connecting each of them by the <code>+</code> sign</span>.</p>
<p>In the above example, <span class="red-text">the coefficient on <code>percep_economy_cps_n</code> is different</span> between <strong>simple</strong> and <strong>multiple linear regression models</strong>. This is because the coefficient on <code>percep_economy_cps_n</code> in the multiple linear regression model reflects the relationship between <code>trudeau_therm_cps</code> and <code>percep_economy_cps_n</code> <span class="red-text">controlling for</span> the other two variables included in the model, <code>ideology</code> and <code>union_d</code>. That is, this coefficient indicates how much <code>truedeau_therm_cps</code> changes, on average, as <code>percep_economy_cps_n</code> increases by one unit, <span class="red-text">holding <code>ideology</code> and <code>union_d</code> constant</span>.</p>
<p>In general, <span class="red-text">the coefficient of the same variable may be different</span> between <strong>simple</strong> and <strong>multiple linear regression models</strong>, if one or some of the control variables included in the multiple linear regression model are <span class="red-text">confounding variables</span> for the relationship between the dependent and the main independent variable of our interest. In the present example, either <code>ideology</code> or <code>union_d</code> or both of them are <span class="red-text">confounding variables</span> to the relationship between <code>trudeau_therm_cps</code> and <code>percep_economy_cps_n</code>. However, the change in the coefficient of <code>percep_economy_cps_n</code> between the simple linear regression model, 18.98, and the multiple linear regression model, 17.19, seems to be small, indicating that the confounding effect of these variables is relatively small in this sample.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
</section>
<section id="sec-dum-ocat-ind" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="sec-dum-ocat-ind"><span class="header-section-number">7.3</span> Dummifying Ordinal Categorical Independent Variable</h2>
<p>In the analysis above, we <span class="red-text">transformed <code>percep_economy_cps</code> to</span> <strong>a <code>numeric</code> variable</strong> before we used it as <span class="red-text">an independent variable</span> in <strong>the <code>lm()</code> function</strong>. Even <span class="red-text">without this transformation</span>, <strong>R</strong> allows the use of <strong>a <code>factor</code></strong> as <span class="red-text">an independent variable</span> in <strong>the <code>lm()</code> function</strong>, but the result is different from the one we saw before for <code>percep_economy_cps_n</code> in <a href="simp_linreg.html#sec-ordinal-ind-var" class="quarto-xref"><span>Section 6.2.1</span></a> and <a href="#sec-lr-multi" class="quarto-xref"><span>Section 7.2</span></a>.</p>
<p>In the code below, I use <code>percep_economy_cps</code> instead of <code>percep_economy_cps_n</code> as <span class="red-text">the only independent variable</span> for a linear regression of <code>trudeau_therm_cps</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> percep_economy_cps, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps, data = ces2019)

Coefficients:
             (Intercept)    percep_economy_cpsSame  percep_economy_cpsBetter  
                   25.13                     23.93                     36.76  </code></pre>
</div>
</div>
<p>In the output above, you see that <code>percep_economy_cps</code> <span class="red-text">is divided into</span> <strong>two variables</strong> <code>percep_economy_cpsSame</code> and <code>percep_economy_cpsBetter</code>, and the coefficients are available for each one of them. What <strong>R</strong> did here is <strong>dummifying</strong> this <strong>categorical variable</strong>.</p>
<p><strong>Dummifying a categorical variable</strong> means that <span class="red-text">each category of</span> <strong>the categorical variable</strong> (<span class="red-text">except for one</span>, which is called <strong>a <span class="red-text">reference</span> category</strong>) is transformed into <strong>a dummy variable for this category</strong>. In the current example, <strong>R</strong> created <strong>two dummy variables</strong> <code>percep_economy_cpsSame</code> and <code>percep_economy_cpsBetter</code>, which are <strong>dummy variables</strong> for <code>percep_economy_cps</code> = <code>Same</code> and <code>percep_economy_cps</code> = <code>Better</code>, created from <code>percep_economy_cps</code> which has three categories (<code>Worse</code> is used as <strong>a <span class="red-text">reference</span> category</strong>).</p>
<p><a href="#tbl-percep" class="quarto-xref">Table&nbsp;<span>7.1</span></a> below shows how the values and categories of <strong>these three variables</strong> correspond to each other.</p>
<div id="tbl-percep" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-percep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7.1: Dummifying percep_economy_cps
</figcaption>
<div aria-describedby="tbl-percep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>percep_economy_cps</th>
<th style="text-align: center;">Worse</th>
<th style="text-align: center;">Same</th>
<th style="text-align: center;">Better</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>percep_economy_cpsSame</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td>percep_economy_cpsBetter</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>As shown in this table, <code>percep_economy_cpsSame</code> is <strong>a dummy variable</strong> whose value equals <code>1</code> if the value of <code>percep_economy_cps</code> is <code>Same</code> and <code>0</code> if the value of <code>percep_economy_cps</code> is <code>Worse</code> or <code>Better</code>.</p>
<p>Similarly, <code>percep_economy_cpsBetter</code> is <strong>a dummy variable</strong> whose value equals <code>1</code> if the value of <code>percep_economy_cps</code> is <code>Better</code> and <code>0</code> if the value of <code>percep_economy_cps</code> is <code>Worse</code> or <code>Same</code>.</p>
<p>In the process of <strong>dummifying a categorical variable</strong>, <strong>a dummy variable</strong> is <span class="red-text">not created for one of the categories</span>, which is used as <strong>a <span class="red-text">reference</span> category</strong> — you will see why this is necessary later. In the example here, <code>Worse</code> is used as <strong>a <span class="red-text">reference</span> category</strong>, and therefore, <strong>a dummy variable</strong> is <span class="red-text">not created</span> for this category.</p>
<p>When <strong>dummifying a categorical variable</strong>, which is stored as a <code>factor</code>, <strong>R</strong> uses <strong>the first <code>level</code></strong> (category) of the variable as <strong>a <span class="red-text">reference</span> category</strong>. Recall that we can check the <code>levels</code> of a <code>factor</code> by <strong>the <code>levels()</code> function</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levels</span>(ces2019<span class="sc">$</span>percep_economy_cps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Worse"  "Same"   "Better"</code></pre>
</div>
</div>
<p>As <strong>the first <code>level</code></strong> of <code>percep_economy_cps</code> is <code>Worse</code>, this <code>level</code> is used as <strong>a <span class="red-text">reference</span> category</strong>, and <strong>dummy variables</strong> are created only for <code>Same</code> and <code>Better</code>, each of which is named <code>percep_economy_cpsSame</code> and <code>percep_economy_cpsBetter</code> using the name of the variable and the name of each <code>level</code>. Because one category is used as <strong>a <span class="red-text">reference</span> category</strong>, if <strong>a categorical variable</strong> has <span class="red-text"><code>L</code> categories</span> (<code>L</code> here is an arbitrary number), then <strong>dummy variables</strong> are <span class="red-text">created for <code>L-1</code> categories</span>. In the present example, there are <span class="red-text">three categories (<code>L = 3</code>)</span> for <code>percep_economy_cps</code>, therefore, only <span class="red-text">two dummy variables (<code>L-1 = 3-1 = 2</code>) are created</span> for this variable.</p>
<section id="sec-dum-ind-fit" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="sec-dum-ind-fit"><span class="header-section-number">7.3.1</span> Fitted Values from the Linear Regression with Dummified Variables from Categorical Independent Variable</h3>
<p>To understand a linear regression model with <strong>the dummified variables</strong> <span class="red-text">created from a categorical independent variable</span> further, let’s derive <span class="red-text">the fitted values of</span> <code>trudeau_therm_cps</code> for each category of <code>percep_economy_cps</code>. Recall that <span class="red-text">a fitted value</span> (or <span class="red-text">a predicted value</span>) is the value of <span class="math inline">\(\widehat{Y}\)</span> derived from a linear regression equation (e.g., <span class="math inline">\(\widehat{Y} = \beta_0 + \beta_1 X_1 + \beta_2 X_2\)</span>) by substituting specific values of independent variables (e.g., specifying <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> at certain values).</p>
<p>Below I reproduced the outcome of the linear regression of <code>trudeau_therm_cps</code> on <code>percep_economy_cps</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> percep_economy_cps, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps, data = ces2019)

Coefficients:
             (Intercept)    percep_economy_cpsSame  percep_economy_cpsBetter  
                   25.13                     23.93                     36.76  </code></pre>
</div>
</div>
<p>Based on this result, <span class="red-text">the fitted values of</span> <code>trudeau_therm_cps</code> can be computed by the following formula.</p>
<!-- : ${\color{blue}25.13}~+~{\color{red}23.93}~\times$ `percep_economy_cpsSame` $+~{\color{violet}36.76}~\times$ `percep_economy_cpsBetter`. -->
<p><span id="eq-fit"><span class="math display">\[
\begin{aligned}
{\color{blue}25.13}~+~{\color{red}23.93}~\times &amp;percep\_economy\_cpsSame\\ &amp;+~{\color{violet}36.76}~\times percep\_economy\_cpsBetter
\end{aligned}
\tag{7.2}\]</span></span></p>
<p>If <code>percep_economy_cps</code> = <code>Worse</code>, then both <code>percep_economy_cpsSame</code> and <code>percep_economy_cpsBetter</code> must be zero (see <a href="#tbl-percep" class="quarto-xref">Table&nbsp;<span>7.1</span></a>). Therefore, substituting <span class="math inline">\(0\)</span> for both variables in <a href="#eq-fit" class="quarto-xref">Equation&nbsp;<span>7.2</span></a>, <span class="red-text">the fitted value of</span> <code>trudeau_therm_cps</code> if <code>percep_economy_cps</code> = <code>Worse</code> is given by <span class="math inline">\({\color{blue}25.13}~+~{\color{red}23.93}\times0+{\color{violet}36.76}\times0 = {\color{blue}25.13}\)</span>. Because both independent variables are zero, <span class="red-text">the fitted value for</span> <code>trudeau_therm_cps</code> when <code>percep_economy_cps</code> = <code>Worse</code> is equivalent to <span class="red-text">the intercept</span> of the linear regression model in <a href="#eq-fit" class="quarto-xref">Equation&nbsp;<span>7.2</span></a>. This is the reason why <span class="red-text">no dummy variable is created</span> for <strong>a <span class="red-text">reference</span> category</strong>. This category <span class="red-text">doesn’t need</span> <strong>its own dummy variable</strong>, since <span class="red-text">the intercept</span> of a linear regression model represents <span class="red-text">the fitted value for</span> <strong>this <span class="red-text">reference</span> category</strong>.</p>
<p>If <code>percep_economy_cps</code> = <code>Same</code>, then <code>percep_economy_cpsSame = 1</code> and <code>percep_economy_cpsBetter = 0</code> (see <a href="#tbl-percep" class="quarto-xref">Table&nbsp;<span>7.1</span></a>). Therefore, substituting these values in <a href="#eq-fit" class="quarto-xref">Equation&nbsp;<span>7.2</span></a>, <span class="red-text">the fitted value of</span> <code>trudeau_therm_cps</code> is given by <span class="math inline">\({\color{blue}25.13}~+~{\color{red}23.93}\times1+{\color{violet}36.76}\times0 = {\color{blue}25.13}~+~{\color{red}23.93} = {\color{red}49.06}\)</span>. This result implies that <strong>the coefficient on <code>percep_economy_cpsSame</code></strong>, <span class="math inline">\({\color{red}23.93}\)</span>, indicates <span class="red-text">the difference in the fitted values of</span> <code>trudeau_therm_cps</code> when <code>percep_economy_cps</code> is <code>Same</code> and when <code>percep_economy_cps</code> is its reference category, <code>Worse</code> (i.e., <span class="math inline">\({\color{red}49.06} - {\color{blue}25.13} = {\color{red}23.93}\)</span>).</p>
<p>Similarly, if <code>percep_economy_cps</code> = <code>Better</code>, then <code>percep_economy_cpsSame = 0</code> and <code>percep_economy_cpsBetter = 1</code> (see <a href="#tbl-percep" class="quarto-xref">Table&nbsp;<span>7.1</span></a>). Therefore, substituting these values in <a href="#eq-fit" class="quarto-xref">Equation&nbsp;<span>7.2</span></a>, <span class="red-text">the fitted value of</span> <code>trudeau_therm_cps</code> is given by <span class="math inline">\({\color{blue}25.13}~+~{\color{red}23.93}\times0+{\color{violet}36.76}\times1 = {\color{blue}25.13}~+~{\color{violet}36.76} = {\color{violet}61.89}\)</span>. Again, <strong>the coefficient on <code>percep_economy_cpsBetter</code></strong>, <span class="math inline">\({\color{violet}36.76}\)</span>, indicates <span class="red-text">the difference in the fitted values</span> between when <code>percep_economy_cps</code> is <code>Better</code> and when <code>percep_economy_cps</code> is its reference category, <code>Worse</code> (i.e., <span class="math inline">\({\color{violet}61.89} - {\color{blue}25.13} = {\color{violet}36.76}\)</span>).</p>
<!-- Here we have computed three different fitted values of `trudeau_therm_cps` for each category of `percep_economy_cps`. Recall that the fitted values of $Y$ are the conditional means of $Y$ modeled by a linear regression. Interestingly, the fitted values of `trudeau_therm_cps` computed for each category of `percep_economy_cps` in the current model are the same as the conditional means of `trudeau_therm_cps` for each category of `percep_economy_cps`.  -->
<!-- Recall that we computed the conditional means of `trudeau_therm_cps` for each category of `percep_economy_cps` in the previous **R Handbook**. I repeated this analysis below. -->
<!-- ```{r} -->
<!-- ces2019 |>  -->
<!--     group_by(percep_economy_cps) |>   -->
<!--     summarize( cond_mean = mean(trudeau_therm_cps, na.rm = TRUE) ) -->
<!-- ``` -->
<!-- As you can see, the conditional means calculated this way are the same as the fitted values of `trudeau_therm_cps` derived above.  -->
</section>
<section id="sec-dum-ind-interpret" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="sec-dum-ind-interpret"><span class="header-section-number">7.3.2</span> How to Interpret the Linear Regression Coefficients on Dummified Variables from Categorical Independent Variable</h3>
<p>More generally, we can say that <strong>the coefficient on a dummy variable</strong> <span class="red-text">created for a certain category</span> of <strong>a categorical independent variable</strong> (say, <span class="math inline">\(X = a\)</span>) indicates <span class="red-text">the difference in the fitted values</span> (<span class="math inline">\(\widehat{Y}\)</span>) for <strong>this category</strong> (<span class="math inline">\(X = a\)</span>) and <strong>the reference category</strong> (<span class="math inline">\(X =\)</span> reference category).</p>
<p>In other words, <strong>the coefficient on a dummy variable</strong> for <span class="red-text">a certain category</span> of <strong>a categorical independent variable</strong> (<span class="math inline">\(X = a\)</span>) tells us <span class="red-text">how the value of <span class="math inline">\(Y\)</span> for the observations with <span class="math inline">\(X = a\)</span> differs, on average, from the value of <span class="math inline">\(Y\)</span> for those with <span class="math inline">\(X =\)</span> reference category</span>.</p>
<p>For example, in <a href="#sec-dum-ind-fit" class="quarto-xref"><span>Section 7.3.1</span></a>, we saw that <strong>the coefficient on <code>percep_economy_cpsSame</code></strong> (<span class="math inline">\({\color{red}23.93}\)</span>) indicates <span class="red-text">the difference in the fitted values of</span> <code>trudeau_therm_cps</code> when <code>percep_economy_cps</code> is <code>Same</code>and <code>percep_economy_cps</code> is the reference category, <code>Worse</code> (<span class="math inline">\({\color{red}49.06} - {\color{blue}25.13} = {\color{red}23.93}\)</span>). This coefficient, <span class="math inline">\({\color{red}23.93}\)</span>, can be interpreted that <span class="red-text">the Trudeau thermometer</span> for the respondents whose perception of economy is <code>Same</code> is <span class="red-text">greater, on average, by <span class="math inline">\({\color{red}23.93}\)</span> points</span> from those whose perception of economy is <span class="red-text">the reference category</span>, <code>Worse</code>.</p>
<p>We also saw that <strong>the coefficient on <code>percep_economy_cpsBetter</code></strong> (<span class="math inline">\({\color{violet}36.76}\)</span>) indicates <span class="red-text">the difference in the fitted values</span> between when <code>percep_economy_cps</code> is <code>Better</code> and when <code>percep_economy_cps</code> is the reference category, <code>Worse</code> (<span class="math inline">\({\color{violet}61.89} - {\color{blue}25.13} = {\color{violet}36.76}\)</span>). This coefficient, <span class="math inline">\({\color{violet}36.76}\)</span>, can be interpreted that <span class="red-text">the Trudeau thermometer</span> for the respondents whose perception of economy is <code>Better</code> is <span class="red-text">greater, on average, by <span class="math inline">\({\color{violet}36.76}\)</span> points</span> from those whose perception of economy is <span class="red-text">the reference category</span>, <code>Worse</code>.</p>
<p>As we saw in these examples, <strong>the coefficient on the dummy variable</strong> for <span class="red-text">a certain category</span> of <strong>a categorical independent variable</strong> (<span class="math inline">\(X = a\)</span>) should be understood as <span class="red-text">the difference in the average value of <span class="math inline">\(Y\)</span></span> for <strong>this category</strong> (<span class="math inline">\(X = a\)</span>) and <span class="red-text">the average value of <span class="math inline">\(Y\)</span></span> for <strong>the <span class="red-text">reference</span> category</strong> (<span class="math inline">\(X =\)</span> reference category). This is the reason why <strong>a <span class="red-text">reference</span> category</strong> is named that way.</p>
<p>As the above discussion has made it clear, <strong>the coefficient on the dummy variable</strong> for <span class="red-text">a certain category</span> of <strong>a categorical independent variable</strong> (<span class="math inline">\(X = a\)</span>) tells us <span class="red-text">the comparison between</span> <strong>the chosen category</strong> (<span class="math inline">\(X = a\)</span>) and <strong>the <span class="red-text">reference</span> category</strong> (<span class="math inline">\(X =\)</span> reference category).</p>
<p>If we want to <span class="red-text">compare</span> <strong>the chosen category</strong> (<span class="math inline">\(X = a\)</span>) with <strong>another category which is <span class="red-text">not</span> the <span class="red-text">reference</span> category</strong> (say, <span class="math inline">\(X = b\)</span>), then we need to <span class="red-text">compute the difference</span> from <strong>their coefficients</strong>.</p>
<p>For example, suppose that we want to <span class="red-text">compare the average Trudeau thermometer</span> between the respondents whose perception of economy is <code>Better</code> and those whose is <code>Same</code>. The comparison is made by taking <span class="red-text">the difference of the fitted values of</span> <code>trudeau_therm_cps</code> when <code>percep_economy_cps</code> is <code>Better</code> and when <code>percep_economy_cps</code> is <code>Same</code>. As we have seen, <span class="red-text">the fitted value of</span> <code>trudeau_therm_cps</code> when <code>percep_economy_cps</code> is <code>Better</code> is <span class="math inline">\({\color{blue}25.13}~+~ {\color{violet}36.76} = {\color{violet}61.89}\)</span> , and the fitted value of <code>trudeau_therm_cps</code> when <code>percep_economy_cps</code> is <code>Same</code> is <span class="math inline">\({\color{blue}25.13}~+~{\color{red}23.93} = {\color{red}49.06}\)</span>. Therefore, <span class="red-text">the difference of these fitted values</span> is <span class="math inline">\({\color{violet}61.89} - {\color{red}49.06} = {\color{brown}12.83}\)</span>.</p>
<p>However, this is equivalent to <span class="red-text">the difference between</span> <strong>the coefficient of <code>percep_economy_cpsBetter</code></strong>, <span class="math inline">\({\color{violet}36.76}\)</span>, <span class="red-text">and</span> <strong>the coefficient of <code>percep_economy_cpsSame</code></strong>, <span class="math inline">\({\color{red}23.93}\)</span>, (<span class="math inline">\({\color{violet}36.76} - {\color{red}23.93} = {\color{brown}12.83}\)</span>). Therefore, we just needed to compute <span class="red-text">the difference between</span> <strong>the coefficient of <code>percep_economy_cpsBetter</code></strong> <span class="red-text">and</span> <strong>the coefficient of <code>percep_economy_cpsSame</code></strong> in the first place.</p>
<p>This resut can be interpreted that <span class="red-text">the Trudeau thermometer</span> for the respondents whose perception of economy is <code>Better</code> is <span class="red-text">greater, on average, by <span class="math inline">\({\color{brown}12.83}\)</span> points</span> from those whose perception of economy is <code>Same</code>.</p>
</section>
<section id="with-additional-independent-variables" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="with-additional-independent-variables"><span class="header-section-number">7.3.3</span> With Additional Independent Variables</h3>
<p>In <a href="#sec-dum-ind-interpret" class="quarto-xref"><span>Section 7.3.2</span></a>, we included only the dummy variables for a categorical independent variable on the right-hand side of the linear regression model. We can also include <span class="red-text">the additional independent variables</span> on <strong>the right hand side</strong>. For example, below I added <code>ideology</code> and <code>union_d</code> on <strong>the right-hand side</strong> of <span class="red-text">the linear regression model of <code>trudeau_therm_cps</code> on <code>percep_economy_cps</code></span>.</p>
<!-- At the end of the previous section, we see that the conditional means of `trudeau_therm_cps` across `percep_economy_cps` are the same as the fitted values of `trudeau_therm_cps` computed from a linear regression model of `trudeau_therm_cps` on the dummified variables from `percep_economy_cps`. This equivalence of the conditional means of $Y$ and the fitted values of $Y$ holds true, if we include **only the dummified variables from a categorical independent variable** on the right hand side of a linear regression model. If we include additional independent variables, this equivalence no longer holds true, because the coefficients of dummified categorical variables model the conditional mean of $Y$ for a specific category of the categorical variable *controlling for other independent variables*. For example, below I fitted a linear regression model of `trudeau_therm_cps` on `percep_economy_cps` and `ideology`. -->
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> percep_economy_cps <span class="sc">+</span> ideology <span class="sc">+</span> union_d, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps + ideology + 
    union_d, data = ces2019)

Coefficients:
             (Intercept)    percep_economy_cpsSame  percep_economy_cpsBetter  
                 39.3833                   22.0875                   33.8127  
                ideology               union_dTRUE  
                 -2.6315                    0.7463  </code></pre>
</div>
</div>
<!-- In this case, we can derive three different equations for the fitted values of `trudeau_therm_cps` across the values of `ideology` for each category of `percep_economy_cps`. First, when `percep_economy_cps` = `Worse`, both `percep_economy_cpsSame = 0` and `percep_economy_cpsBetter = 0`, and therefore, substituting $0$ for both variables, the fitted value of `trudeau_therm_cps` given `ideology` is provided by ${\color{blue}39.56} - 2.61 \times$ `ideology`. This suggests that the intercept of this linear regression model (${\color{blue}39.56}$) indicates the intercept of the model of `trudeau_therm_cps` on `ideology` when `percep_economy_cps` is `Worse`. -->
<!-- Second, when `percep_economy_cps` = `Same`, `percep_economy_cpsSame = 1` and `percep_economy_cpsBetter = 0`, and therefore, the fitted value of `trudeau_therm_cps` given `ideology` is provided by $({\color{blue}39.56} + {\color{red}21.99}) - 2.61 \times$ `ideology` = ${\color{red}61.55} - 2.61 \times$ `ideology`. In other words, the intercept for the model of `trudeau_therm_cps` on `ideology` when `percep_economy_cps` is `Same` is ${\color{red}61.55}$. This result indicates that the coefficient on `percep_economy_cpsSame` (${\color{red}21.99}$)is the difference in the intercept of the model of `trudeau_therm_cps` on `ideology` when `percep_economy_cps` is `Same` (${\color{blue}39.56}$) and `Worse` (${\color{red}61.55}$).  -->
<!-- More generally, we can say that the coefficient on a dummified categorical independent variable (say, $X$) for a certain category (e.g., $X = a$) indicates the difference in the intercept for multiple linear regression models of the dependent variable ($Y$) of our interest on other independent variables ($Z$) between this category (when $X = a$) and a reference category (when $X = reference~category$). -->
<!-- Similarly, when `percep_economy_cps` = `Better`, `percep_economy_cpsSame = 0` and `percep_economy_cpsBetter = 1`, and therefore, the fitted value of `trudeau_therm_cps` given `ideology` is provided by ${\color{blue}39.56} + {\color{violet}33.68} - 2.61 \times$ `ideology` = ${\color{violet}73.24} - 2.61 \times$ `ideology`. In other words, the intercept for the model of `trudeau_therm_cps` on `ideology` when `percep_economy_cps` is `Better` is ${\color{violet}73.24}$. The coefficient on `percep_economy_cpsBetter` (${\color{violet}33.68}$) is the difference in the intercept of the model of `trudeau_therm_cps` on `ideology` when `percep_economy_cps` is `Better` (${\color{violet}73.24}$) and `Worse` (${\color{blue}39.56}$).  -->
<!-- Since the coefficient of `percep_economy_cpsSame` is  -->
<!-- From the result above, we can also interpret that controlling for the respondent's ideology, the feeling thermometer about Trudeau improves, on average, by  -->
<p>As before, in this linear regression analysis, <code>percep_economy_cps</code> is <span class="red-text">dummified into</span> <strong>two dummy variables</strong>, <code>percep_economy_cpsSame</code> and <code>percep_economy_cpsBetter</code>. The interpretation of the coefficients of these dummy variables is the same as before except that the other variables <code>ideology</code> and <code>union_d</code> are now controlled for.</p>
<p><strong>The coefficient of <code>percep_economy_cpsSame</code></strong> is <span class="math inline">\({\color{red}22.09}\)</span>. This can be interpreted that <span class="red-text">the Trudeau thermometer</span> for the respondents whose perception of economy is <code>Same</code> is <span class="red-text">greater, on average, by <span class="math inline">\({\color{red}22.09}\)</span> points</span> from those whose perception of economy is the reference category, <code>Worse</code>, <span class="red-text">controlling for</span> the respondents’ <span class="red-text">political ideology</span> and <span class="red-text">union membership</span>.</p>
<p><strong>The coefficient of <code>percep_economy_cpsBetter</code></strong> is <span class="math inline">\({\color{violet}33.81}\)</span>. This coefficient, <span class="math inline">\({\color{violet}33.81}\)</span>, can be interpreted that <span class="red-text">the Trudeau thermometer</span> for the respondents whose perception of economy is <code>Better</code> is <span class="red-text">greater, on average, by <span class="math inline">\({\color{violet}33.81}\)</span> points</span> from those whose perception of economy is the reference category, <code>Worse</code>, <span class="red-text">holding their political ideology and union membership constant</span>.</p>
<p>If we want to <span class="red-text">compare</span> the respondents whose perception of economy is <code>Better</code> and those whose is <code>Same</code>, we need to <span class="red-text">compute the difference between</span> <strong>the coefficient of <code>percep_economy_cpsBetter</code></strong> <span class="red-text">and</span> <strong>the coefficient of <code>percep_economy_cpsSame</code></strong> (<span class="math inline">\({\color{violet}33.81} - {\color{red}22.09} = {\color{brown}11.72}\)</span>). As the difference is <span class="math inline">\({\color{brown}11.72}\)</span>, it can be interpreted that <span class="red-text">the Trudeau thermometer</span> for the respondents whose perception of economy is <code>Better</code> is <span class="red-text">greater, on average, by <span class="math inline">\({\color{brown}11.72}\)</span> points</span> from those whose perception of economy is <code>Same</code>, <span class="red-text">with the respondents’ political ideology and union status held constant</span>.</p>
</section>
<section id="difference-from-numerical-version" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="difference-from-numerical-version"><span class="header-section-number">7.3.4</span> Difference from Numerical Version</h3>
<p>Comparing the linear regression results of <strong>the <code>numeric</code> version</strong> and <strong>the dummified version</strong> of <code>percep_economy_cps</code>, we can see <span class="red-text">the difference in these two specifications</span>.</p>
<p>For your quick reference, I have reproduced the outputs of <strong>the <code>lm()</code> function</strong> for <span class="red-text">a simple linear regression</span> of <code>trudeau_therm_cps</code> with both versions of <code>percep_economy_cps</code> below.</p>
<p>(1) With <strong>the <code>numeric</code> version</strong> of <code>percep_economy_cps</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps_n, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n  
               8.128                18.982  </code></pre>
</div>
</div>
<p>(2) With <strong>the dummified version</strong> of <code>percep_economy_cps</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps, data = ces2019)

Coefficients:
             (Intercept)    percep_economy_cpsSame  percep_economy_cpsBetter  
                   25.13                     23.93                     36.76  </code></pre>
</div>
</div>
<p>In the result of <span class="red-text">a simple linear regression model</span> with <strong>the <code>numeric</code> version</strong>, <code>percep_economy_cps_n</code>, <span class="red-text">the average difference in the Trudeau thermometer</span> is <span class="math inline">\(18.98\)</span> points both between <code>Better</code> and <code>Same</code> and between <code>Same</code> and <code>Worse</code>. On the other hand, in the linear regression model with <strong>the dummified version</strong>, <span class="red-text">the average difference in the Trudeau thermometer</span> is <span class="math inline">\({\color{violet}36.76} - {\color{red}23.93} = {\color{brown}12.83}\)</span> points between <code>Better</code> and <code>Same</code>, while it is <span class="math inline">\({\color{red}23.93}\)</span> points between <code>Same</code> and <code>Worse</code>.</p>
<p>Similarly, I have reproduced the outputs of <strong>the <code>lm()</code> function</strong> for <span class="red-text">a multiple linear regression</span> of <code>trudeau_therm_cps</code> with both versions of <code>percep_economy_cps</code> below.</p>
<p>(1) With <strong>the <code>numeric</code> version</strong> of <code>percep_economy_cps</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps_n + ideology + 
    union_d, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n              ideology  
             24.7569               17.1926               -2.7193  
         union_dTRUE  
              0.8752  </code></pre>
</div>
</div>
<p>(2) With <strong>the dummified version</strong> of <code>percep_economy_cps</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps + ideology + 
    union_d, data = ces2019)

Coefficients:
             (Intercept)    percep_economy_cpsSame  percep_economy_cpsBetter  
                 39.3833                   22.0875                   33.8127  
                ideology               union_dTRUE  
                 -2.6315                    0.7463  </code></pre>
</div>
</div>
<p>In the result of <span class="red-text">a multiple linear regression model</span> with <strong>the <code>numeric</code> version</strong>, <code>percep_economy_cps_n</code>, <span class="red-text">the average difference in the Trudeau thermometer</span> is <span class="math inline">\(17.19\)</span> points both between <code>Better</code> and <code>Same</code> and between <code>Same</code> and <code>Worse</code>. On the other hand, in the result with <strong>the dummified version</strong>, <span class="red-text">the average difference in the Trudeau thermometer</span> is <span class="math inline">\({\color{violet}33.81} - {\color{red}22.09} = {\color{brown}11.72}\)</span> points between <code>Better</code> and <code>Same</code>, while it is <span class="math inline">\({\color{red}22.09}\)</span> points between <code>Same</code> and <code>Worse</code>.</p>
<p>When we used <strong>the <code>numeric</code> version</strong>, <code>percep_economy_cps_n</code>, <span class="red-text">the difference in Trudeau thermometer</span> is <span class="red-text">the same</span> whether we consider the difference between <code>Better</code> and <code>Same</code> or that between <code>Same</code> and <code>Worse</code>. On the other hand, when we used <strong>the dummified version</strong>, <span class="red-text">the difference in Trudeau thermometer</span> is <span class="red-text">different</span> when we consider the difference between <code>Better</code> and <code>Same</code> and when we examine the difference between <code>Same</code> and <code>Worse</code>. <!-- In fact, the difference between `Better` and `Same` is about half of that between `Same` and `Worse`. However, if we consider the difference between `Better` and `Worse`, it is almost the same between the models with the `numeric` version ($37.96$ in a simple linear regression and $34.38$ in a multiple linear regression) and the dummified version ($36.76$ in a simple linear regression and $33.81$ in a multiple linear regression). --></p>
<p>In general, <span class="red-text">the average difference in the dependent variable</span> between one category of ordinal categorical variable and its adjacent category is <span class="red-text">the same for all categories</span>, if we use <strong>a <code>numeric</code> version</strong> of <strong>an ordinal categorical variable</strong>, but it is <span class="red-text">different for all categories</span> of this variable, if we use <strong>the dummified version</strong> of this variable. Hence, <strong>dummification</strong> may be considered as <span class="red-text">a more flexible modeling strategy</span> for <strong>an ordinal categorical variable</strong> than the use of <strong>a <code>numeric</code> version</strong> of this variable. This is <span class="red-text">a modeling choice we need to make</span> when we include <strong>an ordinal categorical variable</strong> as <span class="red-text">an independent variable</span> in <span class="red-text">our linear regression model</span>.</p>
<!-- By the way, if we include only the dummified variables from an ordinal categorical variable on the right hand side of a linear regression model, the fitted values of `trudeau_therm_cps` computed for each category of `percep_economy_cps` are the same as the conditional means of `trudeau_therm_cps` for each category of `percep_economy_cps`.  -->
<!-- Recall that we computed the conditional means of `trudeau_therm_cps` for each category of `percep_economy_cps` in the previous **R Handbook**. I repeated this analysis below. -->
<!-- ```{r} -->
<!-- ces2019 |> -->
<!--     group_by(percep_economy_cps) |> -->
<!--     summarize( cond_mean = mean(trudeau_therm_cps, na.rm = TRUE) ) -->
<!-- ``` -->
<!-- As you can see, the conditional means calculated this way are the same as the fitted values of `trudeau_therm_cps` derived above. -->
<!-- This equivalence of the conditional means of $Y$ and the fitted values of $Y$ from a linear regression model holds true, only when we include **only the dummified variables from a categorical independent variable** on the right hand side of a linear regression model. If we include additional independent variables, this equivalence no longer holds, because the coefficients of dummified categorical variables model the conditional mean of $Y$ for a specific category of the categorical variable *controlling for other independent variables*.  -->
<!-- In fact, when we include additional independent variables, the intercept and the coefficients of the dummified variables from a categorical independent variable together represent different intercepts for different categories specified by this categorical independent variable. -->
<!-- For example, the fitted values for the linear regression model of `trudeau_therm_cps` on  this model can be derived from the following equation: ${\color{blue}39.56} + {\color{red}21.99}~\times$ `percep_economy_cpsSame` $+~{\color{violet}33.68}~\times$ `percep_economy_cpsBetter` $- 2.61 \times$ `ideology`.  -->
</section>
</section>
<section id="sec-dum-ncat-ind-q" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="sec-dum-ncat-ind-q"><span class="header-section-number">7.4</span> Dummifying Nominal Categorical Independent Variable: Questions</h2>
<p>For <strong>an ordinal categorical variable</strong>, we can consider <strong>dummifying it</strong> and <strong>transforming it into a <code>numeric</code> variable</strong> as <span class="red-text">alternatives</span>, but for <strong>a <span class="red-text">nominal</span> categorical variable</strong>, <strong>dummifying</strong> may be <span class="red-text">the only appropriate option</span>. As the interpretation of the results remain the same as in <a href="#sec-dum-ocat-ind" class="quarto-xref"><span>Section 7.3</span></a>, instead of repeating the explanation on how to interpret a model, I want you to work on the following questions on <strong>dummifying</strong> <span class="red-text">a nominal categorical independent variable</span>. Answers to these questions will be made available in <a href="#sec-dum-ncat-ind-a" class="quarto-xref"><span>Section 7.5</span></a> after all tutorial sections have covered this chapter.</p>
<!-- when we use [independent variables dummified from]{.red-text} **a nominal categorical variable** in [a linear regression model]{.red-text} is the same as the interpretation for dummified independent variables from an ordinal categorical variable in @sec-dum-ocat-ind.  -->
<p>&nbsp;</p>
<p>Let’s use <strong>the province of residence of the respondents</strong> (<code>province</code>) in the <code>ces2019</code> data frame as an example.</p>
<p>&nbsp;</p>
<p><strong>Question 1</strong><br>
What will be <span class="red-text">a reference category</span> when we <strong>dummify</strong> <code>province</code> on <strong>the right hand side</strong> of <span class="red-text">a linear regression model</span> using <strong>the <code>lm()</code> function</strong>? Use <strong>the <code>levels()</code> function</strong> to find out.</p>
<p>&nbsp;</p>
<p><strong>Question 2</strong><br>
Fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>province</code></span> using <strong>the <code>lm()</code> function</strong>. Interpret <strong>the intercept</strong> and <strong>the coefficient on <code>provinceON</code></strong>.</p>
<p>&nbsp;</p>
<p><strong>Question 3</strong><br>
Fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>province</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code></span> using <strong>the <code>lm()</code> function</strong>. Interpret <strong>the coefficients on <code>provinceON</code>, <code>provinceSK</code>, and <code>percep_economy_cps_n</code></strong>, respectively.</p>
<p>&nbsp;</p>
<p><strong>Question 4</strong><br>
<strong>Dummifying</strong> <span class="red-text">all categories</span> except one is not the only way to create a dummy variable from <strong>a nominal categorical variable</strong>. An alternative is to create <strong>a dummy variable</strong> only for <span class="red-text">a single category</span> or <span class="red-text">a subset of categories</span> of <strong>a nominal categorical variable</strong>. In this question, we consider <strong>a <span class="red-text">single</span> dummy variable</strong> for a subset of categories of <code>province</code>.</p>
<p>Suppose we theorized that the respondents’ feelings about the incumbent Liberal prime minister are different between <strong>the Prairies (Alberta, Manitoba, and Saskatchewan)</strong> and <strong>the rest of the provinces</strong>. In this case, we want to <span class="red-text">dummify <code>province</code> such that</span> <code>prairies</code> = 1 if the respondents lived in these provinces and <code>prairies</code> = 0 otherwise. We can create such a variable by <strong>the <code>ifelse()</code> function</strong> introduced in <a href="simp_linreg.html#sec-dummy-dep-var" class="quarto-xref"><span>Section 6.3.4</span></a>. Read that section again to review the basics of <strong>the <code>ifelse()</code> function</strong>. For the current purpose, you may specify <span class="red-text">the condition</span> in <strong>the <code>ifelse()</code> function</strong> as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Create a new variable "prairies" using the ifelse() function.</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">prairies =</span> <span class="fu">ifelse</span>(province <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AB"</span>,<span class="st">"MB"</span>,<span class="st">"SK"</span>), <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>) )</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                        <span class="co"># This ifelse() function assigns "TRUE" to observations if</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                        <span class="co"># "province" is "AB", "MB" or "SK" but assigns "FALSE" otherwise.</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Then, we transform prairies into a logical variable.</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, <span class="at">prairies =</span> <span class="fu">as.logical</span>(prairies) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above code, <span class="red-text">the condition</span> for <strong>the <code>ifelse()</code> function</strong> is specified as <code>province %in% c("AB","MB","SK")</code>, which means that “<code>province</code> is either <code>AB</code> or <code>MB</code> or <code>SK</code>.” If you want to specify <span class="red-text">a condition that a certain variable, say <code>var</code>, equals either <code>A</code> or <code>B</code> or <code>C</code> or <code>D</code></span>, you can use <strong><code>%in%</code></strong> to specify <span class="red-text">the condition as</span> <strong><code>var %in% c("A","B","C","D")</code></strong>.</p>
<p>Let’s check if <code>prairies</code> was created as we wanted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>prairies, ces2019<span class="sc">$</span>province, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
         AB  BC  MB  NB  NL  NS  ON  PE  QC  SK &lt;NA&gt;
  FALSE   0 804   0 201 201 200 807 201 802   0    0
  TRUE  282   0 261   0   0   0   0   0   0 262    0
  &lt;NA&gt;    0   0   0   0   0   0   0   0   0   0    0</code></pre>
</div>
</div>
<p>Fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>prairies</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code></span> using <strong>the <code>lm()</code> function</strong>.</p>
<p>Interpret <strong>the coefficient on <code>prairiesTRUE</code></strong>.</p>
<p>&nbsp;</p>
<p><strong>Question 5</strong><br>
We may also use <strong>multiple dummy variables</strong> corresponding to <span class="red-text">different subsets of a nominal categorical variable</span>. Suppose we theorized that, in addition to <strong>the Prairies</strong>, the respondents’ feelings about the incumbent Liberal prime minister may also be different in <strong>the Maritimes (New Brunswick, Nova Scotia, and Prince Edward Island)</strong> from <strong>the rest of the provinces</strong>.</p>
<p>Create <strong>a dummy variable for the Maritimes, named <code>maritimes</code></strong>, using <strong>the <code>ifelse()</code> function</strong>. Then, fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>prairies</code>, <code>maritimes</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code></span> using <strong>the <code>lm()</code> function</strong>.</p>
<p>Interpret <strong>the coefficients on <code>prairiesTRUE</code> and <code>maritimesTRUE</code></strong>, respectively.</p>
</section>
<section id="sec-dum-ncat-ind-a" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="sec-dum-ncat-ind-a"><span class="header-section-number">7.5</span> Dummifying Nominal Categorical Independent Variable: Answers</h2>
<p><span class="red-text">Answers to the questions</span> posed in <a href="#sec-dum-ncat-ind-q" class="quarto-xref"><span>Section 7.4</span></a> will be made available here after all tutorial sections have covered this chapter. Schedule to come back to review these answers.</p>
<p>&nbsp;</p>
<p>Let’s use <strong>the province of residence of the respondents</strong> (<code>province</code>) in the <code>ces2019</code> data frame as an example.</p>
<p>&nbsp;</p>
<p><strong>Question 1</strong><br>
What will be <span class="red-text">a reference category</span> when we <strong>dummify</strong> <code>province</code> on <strong>the right hand side</strong> of <span class="red-text">a linear regression model</span> using <strong>the <code>lm()</code> function</strong>? Use <strong>the <code>levels()</code> function</strong> to find out.</p>
<p>Below is a list of levels of this variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levels</span>(ces2019<span class="sc">$</span>province)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "AB" "BC" "MB" "NB" "NL" "NS" "ON" "PE" "QC" "SK"</code></pre>
</div>
</div>
<p>Because the first level is <code>AB</code>, <strong>Alberta</strong> will be used as <span class="red-text">a reference category</span>.</p>
<p>&nbsp;</p>
<p><strong>Question 2</strong><br>
Fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>province</code></span> using <strong>the <code>lm()</code> function</strong>. Interpret <strong>the intercept</strong> and <strong>the coefficient on <code>provinceON</code></strong>.</p>
<p>We fit a linear regression model of <code>trudeau_therm_cps</code> on <code>province</code> as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> province, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ province, data = ces2019)

Coefficients:
(Intercept)   provinceBC   provinceMB   provinceNB   provinceNL   provinceNS  
     24.910       17.566       12.487       21.535       22.019       23.955  
 provinceON   provincePE   provinceQC   provinceSK  
     24.083       24.600       24.225        3.426  </code></pre>
</div>
</div>
<!-- Because [the dummified variables]{.red-text} from **a nominal categorical variable** (`province`) are [the only independent variables]{.red-text} included on **the right-hand side** of this linear regression model,  -->
<p><strong>The intercept</strong> is <span class="red-text">the fitted value for the reference category</span> of this variable (<code>province</code>). Since the reference category is <strong>Alberta</strong>, the intercept is <span class="red-text">the fitted value for</span> <strong>Alberta</strong>. The intercept in the above linear regression result is <span class="math inline">\(24.91\)</span>. This may be interpreted as follows.</p>
<p>“Feeling thermometer about Trudeau is, on average, 24.91 points for those respondents who lived in <strong>Alberta</strong>.”</p>
<p><strong>The coefficient on a dummy variable</strong> for <span class="red-text">one categocy of</span> <strong>a nominal categorical variable</strong> represents <span class="red-text">the difference in the average value of the dependent variable</span> between the observations for which the variable is <span class="red-text">this category</span> and those for which the variable is <span class="red-text">the reference category</span>. Because <strong>the coefficient of <code>provinceON</code></strong> is <span class="math inline">\(24.08\)</span>, and the reference category is <strong>Alberta</strong>, this coefficient may be interpreted as follows.</p>
<p>“Feeling thermometer about Trudeau is, on average, 24.08 points higher for those respondents who lived in <strong>Ontario</strong> than those who lived in <strong>Alberta</strong>.”</p>
<p>&nbsp;</p>
<p><strong>Question 3</strong><br>
Fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>province</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code></span> using <strong>the <code>lm()</code> function</strong>. Interpret <strong>the coefficients on <code>provinceON</code>, <code>provinceSK</code>, and <code>percep_economy_cps_n</code></strong>, respectively.</p>
<p>We fit a linear regression model of <code>trudeau_therm_cps</code> on <code>province</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code> as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> province <span class="sc">+</span> percep_economy_cps_n</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="sc">+</span> ideology <span class="sc">+</span> union_d, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ province + percep_economy_cps_n + 
    ideology + union_d, data = ces2019)

Coefficients:
         (Intercept)            provinceBC            provinceMB  
             15.2848               11.7557               10.8040  
          provinceNB            provinceNL            provinceNS  
             16.9362               18.4670               12.1679  
          provinceON            provincePE            provinceQC  
             15.3387               15.8607               12.3670  
          provinceSK  percep_economy_cps_n              ideology  
              3.4424               15.8163               -2.6628  
         union_dTRUE  
              0.5959  </code></pre>
</div>
</div>
<p>Because there are <span class="red-text">additional control variables</span>, <strong>the coefficient on a dummy variable</strong> for <span class="red-text">one category of</span> <strong>a nominal categorical variable</strong> represents <span class="red-text">the difference in the average value of the dependent variable</span> between the observations for which the variable is <span class="red-text">this category</span> and those for which the variable is <span class="red-text">the reference category</span>, <span class="red-text"><strong>controlling for other control variables</strong></span>.</p>
<p><strong>The coefficient of <code>provinceON</code></strong> can be interpreted as follows.</p>
<p>“Feeling thermometer about Trudeau is, on average, 15.34 points higher for those respondents who lived in Ontario than those who lived in Alberta, <span class="red-text">controlling for the perception of economy, political ideology, and union membership</span>.”</p>
<p><strong>The coefficients on <code>provinceSK</code></strong> can be interpreted as follows.</p>
<p>“Feeling thermometer about Trudeau is, on average, 3.44 points higher for those respondents who lived in Saskatchewan than those who lived in Alberta, <span class="red-text">holding the perception of economy, political ideology, and union membership constant</span>.”</p>
<p><strong>The coefficients on <code>percep_economy_cps_n</code></strong> can be interpreted as below.</p>
<p>“Feeling thermometer about Trudeau is, on average, 15.82 points higher for those respondents whose perception of economy is <code>better</code> (<code>the same</code>) than those whose perception of economy is <code>the same</code> (<code>worse</code>), <span class="red-text">controlling for the provinces of residence, political ideology, and union membership</span>.”</p>
<p>&nbsp;</p>
<p><strong>Question 4</strong><br>
<strong>Dummifying</strong> <span class="red-text">all categories</span> except one is not the only way to create a dummy variable from <strong>a nominal categorical variable</strong>. An alternative is to create <strong>a dummy variable</strong> only for <span class="red-text">a single category</span> or <span class="red-text">a subset of categories</span> of <strong>a nominal categorical variable</strong>. In this question, we consider <strong>a <span class="red-text">single</span> dummy variable</strong> for a subset of categories of <code>province</code>.</p>
<p>Suppose we theorized that the respondents’ feelings about the incumbent Liberal prime minister are different between <strong>the Prairies (Alberta, Manitoba, and Saskatchewan)</strong> and <strong>the rest of the provinces</strong>. In this case, we want to <span class="red-text">dummify <code>province</code> such that</span> <code>prairies</code> = 1 if the respondents lived in these provinces and <code>prairies</code> = 0 otherwise. We can create such a variable by <strong>the <code>ifelse()</code> function</strong> introduced in <a href="simp_linreg.html#sec-dummy-dep-var" class="quarto-xref"><span>Section 6.3.4</span></a>. Read that section again to review the basics of <strong>the <code>ifelse()</code> function</strong>. For the current purpose, you may specify <span class="red-text">the condition</span> in <strong>the <code>ifelse()</code> function</strong> as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Create a new variable "prairies" using the ifelse() function.</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">prairies =</span> <span class="fu">ifelse</span>(province <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AB"</span>,<span class="st">"MB"</span>,<span class="st">"SK"</span>), <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>) )</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                        <span class="co"># This ifelse() function assigns "TRUE" to observations if</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                        <span class="co"># "province" is "AB", "MB" or "SK" but assigns "FALSE" otherwise.</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Then, we transform prairies into a logical variable.</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, <span class="at">prairies =</span> <span class="fu">as.logical</span>(prairies) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the above code, <span class="red-text">the condition</span> for <strong>the <code>ifelse()</code> function</strong> is specified as <code>province %in% c("AB","MB","SK")</code>, which means that “<code>province</code> is either <code>AB</code> or <code>MB</code> or <code>SK</code>.” If you want to specify <span class="red-text">a condition that a certain variable, say <code>var</code>, equals either <code>A</code> or <code>B</code> or <code>C</code> or <code>D</code></span>, you can use <strong><code>%in%</code></strong> to specify <span class="red-text">the condition as</span> <strong><code>var %in% c("A","B","C","D")</code></strong>.</p>
<p>Let’s check if <code>prairies</code> was created as we wanted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>prairies, ces2019<span class="sc">$</span>province, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
         AB  BC  MB  NB  NL  NS  ON  PE  QC  SK &lt;NA&gt;
  FALSE   0 804   0 201 201 200 807 201 802   0    0
  TRUE  282   0 261   0   0   0   0   0   0 262    0
  &lt;NA&gt;    0   0   0   0   0   0   0   0   0   0    0</code></pre>
</div>
</div>
<p>Fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>prairies</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code></span> using <strong>the <code>lm()</code> function</strong>.</p>
<p>Interpret <strong>the coefficient on <code>prairiesTRUE</code></strong>.</p>
<p>We fit a linear regression model of <code>trudeau_therm_cps</code> on prairies, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code> as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> prairies <span class="sc">+</span> percep_economy_cps_n</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="sc">+</span> ideology <span class="sc">+</span> union_d, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ prairies + percep_economy_cps_n + 
    ideology + union_d, data = ces2019)

Coefficients:
         (Intercept)          prairiesTRUE  percep_economy_cps_n  
             28.6463               -9.0945               16.0341  
            ideology           union_dTRUE  
             -2.6583                0.6047  </code></pre>
</div>
</div>
<p>Given this <strong>dummy variable for the Prairies</strong>, <span class="red-text">the reference category</span> is <strong>all provinces other than the Prairies</strong>. Therefore, <strong>the coefficient on <code>prairiesTRUE</code></strong> indicates <span class="red-text">the average difference in <code>trudeau_therm_cps</code></span> between the respondents who lived in <strong>the Prairies</strong> and those who lived in <strong>other provinces</strong>, <span class="red-text">controlling for other variables</span>.</p>
<p><strong>The coefficient on <code>prairiesTRUE</code></strong> may be interpreted as follows.</p>
<p>“Feeling thermometer about Trudeau is, on average, 9.09 points lower for those respondents who lived in <strong>the Prairies</strong> than those who lived in <strong>other provinces</strong>, controlling for the perception of economy, political ideology, and union membership.”</p>
<p>&nbsp;</p>
<p><strong>Question 5</strong><br>
We may also use <strong>multiple dummy variables</strong> corresponding to <span class="red-text">different subsets of a nominal categorical variable</span>. Suppose we theorized that, in addition to <strong>the Prairies</strong>, the respondents’ feelings about the incumbent Liberal prime minister may also be different in <strong>the Maritimes (New Brunswick, Nova Scotia, and Prince Edward Island)</strong> from <strong>the rest of the provinces</strong>.</p>
<p>Create <strong>a dummy variable for the Maritimes, named <code>maritimes</code></strong>, using <strong>the <code>ifelse()</code> function</strong>. Then, fit <span class="red-text">a linear regression model of <code>trudeau_therm_cps</code> on <code>prairies</code>, <code>maritimes</code>, <code>percep_economy_cps_n</code>, <code>ideology</code>, and <code>union_d</code></span> using <strong>the <code>lm()</code> function</strong>.</p>
<p>Interpret <strong>the coefficients on <code>prairiesTRUE</code> and <code>maritimesTRUE</code></strong>, respectively.</p>
<p>We create <strong>a new dummy variable <code>maritimes</code></strong> as below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Create a new variable "maritimes" using the ifelse() function.</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">maritimes =</span> <span class="fu">ifelse</span>(province <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"NB"</span>,<span class="st">"NS"</span>,<span class="st">"PE"</span>), <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>) )</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>      <span class="co"># This ifelse() function assigns "TRUE" to observations if</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>      <span class="co"># "province" is "NB", "NS" or "PE" but assigns "FALSE" otherwise.</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, <span class="co"># Then, we transform prairies into a logical variable.</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">prairies =</span> <span class="fu">as.logical</span>(prairies) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check if <code>maritimes</code> was created as we wanted.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>maritimes, ces2019<span class="sc">$</span>province, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
         AB  BC  MB  NB  NL  NS  ON  PE  QC  SK &lt;NA&gt;
  FALSE 282 804 261   0 201   0 807   0 802 262    0
  TRUE    0   0   0 201   0 200   0 201   0   0    0
  &lt;NA&gt;    0   0   0   0   0   0   0   0   0   0    0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> prairies <span class="sc">+</span> maritimes <span class="sc">+</span> percep_economy_cps_n</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="sc">+</span> ideology <span class="sc">+</span> union_d, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ prairies + maritimes + percep_economy_cps_n + 
    ideology + union_d, data = ces2019)

Coefficients:
         (Intercept)          prairiesTRUE         maritimesTRUE  
             28.3114               -8.8188                1.4265  
percep_economy_cps_n              ideology           union_dTRUE  
             16.0503               -2.6527                0.6189  </code></pre>
</div>
</div>
<p>Because the above model includes <strong>dummy variables</strong> for <strong>the Prairies</strong> and <strong>the Maritimes</strong>, <span class="red-text">the reference category</span> is <strong>the provinces other than those in the Prairies and the Maritimes</strong>. Therefore, <strong>the coefficients on <code>prairiesTRUE</code> and <code>maritimesTRUE</code></strong> indicate, respectively, <span class="red-text">the average difference in</span> <code>trudeau_therm_cps</code> between the respondents who lived in <strong>the Prairies</strong> and <strong>Maritimes</strong> and those who lived in <strong>the provinces other than the Prairies and the Maritimes</strong>, controlling for other variables.</p>
<p><strong>The coefficients on <code>prairiesTRUE</code> and <code>maritimesTRUE</code></strong> may be interpreted as follows.</p>
<p>“Feeling thermometer about Trudeau is, on average, 8.82 points lower for those respondents who lived in <strong>the Prairies</strong> than those who lived in <strong>the provinces other than the Prairies and the Maritimes</strong>, controlling for the perception of economy, political ideology, and union membership.”</p>
<p>“Feeling thermometer about Trudeau is, on average, 1.43 points higher for those respondents who lived in <strong>the Maritimes</strong> than those who lived in the provinces <strong>other than the Prairies and the Maritimes</strong>, holding the perception of economy, political ideology, and union membership constant.”</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>A caveat here is that while it is not clear in the analyses presented, the number of observations included is different between these simple and multiple linear regressions. We will come back to this issue later.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./simp_linreg.html" class="pagination-link" aria-label="Simple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./linreg_inf.html" class="pagination-link" aria-label="Statistical Inference for Linear Regression">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistical Inference for Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>