<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Simple Linear Regression – POL232 R Handbook (W2025)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./multi_linreg.html" rel="next">
<link href="./bivariate.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./simp_linreg.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">POL232 R Handbook (W2025)</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Setting Up R &amp; RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Basic Use of RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./des1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Descriptive Statistics (1)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./des2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Descriptive Statistics (2)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bivariate Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./simp_linreg.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multi_linreg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linreg_inf.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistical Inference for Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./subsig.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Substantive Significance</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#linear-regression-for-bivariate-analysis" id="toc-linear-regression-for-bivariate-analysis" class="nav-link active" data-scroll-target="#linear-regression-for-bivariate-analysis"><span class="header-section-number">6.1</span> Linear Regression for Bivariate Analysis</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression"><span class="header-section-number">6.1.1</span> Simple Linear Regression</a></li>
  <li><a href="#scatterplot-with-linear-regression-line" id="toc-scatterplot-with-linear-regression-line" class="nav-link" data-scroll-target="#scatterplot-with-linear-regression-line"><span class="header-section-number">6.1.2</span> Scatterplot with Linear Regression Line</a></li>
  </ul></li>
  <li><a href="#ordinal-categorical-variable-in-simple-linear-regression" id="toc-ordinal-categorical-variable-in-simple-linear-regression" class="nav-link" data-scroll-target="#ordinal-categorical-variable-in-simple-linear-regression"><span class="header-section-number">6.2</span> Ordinal Categorical Variable in Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#sec-ordinal-ind-var" id="toc-sec-ordinal-ind-var" class="nav-link" data-scroll-target="#sec-ordinal-ind-var"><span class="header-section-number">6.2.1</span> Use Ordinal Categorical Variable As Independent Variable</a></li>
  <li><a href="#use-ordinal-categorical-variable-as-dependent-variable" id="toc-use-ordinal-categorical-variable-as-dependent-variable" class="nav-link" data-scroll-target="#use-ordinal-categorical-variable-as-dependent-variable"><span class="header-section-number">6.2.2</span> Use Ordinal Categorical Variable As Dependent Variable</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization"><span class="header-section-number">6.2.3</span> Visualization</a></li>
  </ul></li>
  <li><a href="#dummy-variable-in-simple-linear-regression" id="toc-dummy-variable-in-simple-linear-regression" class="nav-link" data-scroll-target="#dummy-variable-in-simple-linear-regression"><span class="header-section-number">6.3</span> Dummy Variable in Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#dummy-variable-as-logical-variable-in-r" id="toc-dummy-variable-as-logical-variable-in-r" class="nav-link" data-scroll-target="#dummy-variable-as-logical-variable-in-r"><span class="header-section-number">6.3.1</span> Dummy Variable As <code>Logical</code> Variable in R</a></li>
  <li><a href="#use-dummy-variable-as-independent-variable" id="toc-use-dummy-variable-as-independent-variable" class="nav-link" data-scroll-target="#use-dummy-variable-as-independent-variable"><span class="header-section-number">6.3.2</span> Use Dummy Variable As Independent Variable</a></li>
  <li><a href="#use-dummy-variable-as-dependent-variable" id="toc-use-dummy-variable-as-dependent-variable" class="nav-link" data-scroll-target="#use-dummy-variable-as-dependent-variable"><span class="header-section-number">6.3.3</span> Use Dummy Variable As Dependent Variable</a></li>
  <li><a href="#sec-dummy-dep-var" id="toc-sec-dummy-dep-var" class="nav-link" data-scroll-target="#sec-dummy-dep-var"><span class="header-section-number">6.3.4</span> Dummy Dependent Variable Constructed from Nominal Categorical Variable</a></li>
  <li><a href="#visualization-1" id="toc-visualization-1" class="nav-link" data-scroll-target="#visualization-1"><span class="header-section-number">6.3.5</span> Visualization</a></li>
  </ul></li>
  <li><a href="#conditional-means-medians" id="toc-conditional-means-medians" class="nav-link" data-scroll-target="#conditional-means-medians"><span class="header-section-number">6.4</span> Conditional Means &amp; Medians</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-slr" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Simple Linear Regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Before you start</strong> working on this chapter, you need to do the following. If you need a help for each step, see <a href="des1.html#sec-preparation" class="quarto-xref"><span>Section 3.1</span></a>.</p>
<ul>
<li><p>Launch <strong>RStudio</strong>.</p></li>
<li><p>Load <code>POL232.RData</code> into your current <strong>R</strong> session.</p></li>
<li><p>Prepare an <strong>R Script</strong> to save all your work in this chapter. I suggest you name it “<code>POL232_Week#_YourLastName.R</code>” or “<code>POL232_Tutorial#_YourLastName.R</code>” in which <code>#</code> is the number of the current week or tutorial session.</p></li>
<li><p>You also need to load <code>tidyverse</code> package into your current <strong>R</strong> session (<a href="setup.html#sec-load-packages" class="quarto-xref"><span>Section 1.4.2</span></a>).</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>I suggest you <span class="red-text">actually write</span> <strong>the R functions</strong> used below in your <strong>R script</strong> instead of copying and pasting them. See <a href="des1.html#sec-actually-write-rscript" class="quarto-xref"><span>Section 3.1.5</span></a> for <span class="red-text">why</span>.</p></li>
<li><p>I also suggest you <span class="red-text">sufficiently annotate</span> your <strong>R script</strong> (i.e.&nbsp;leaving notes after the <code>#</code> sign) so that you can use your <strong>R script</strong> as your reference when you work on tutorial exercises or data analysis paper assignments. In other words, this <strong>R script</strong> will be <span class="red-text">your notes for this chapter</span>.</p></li>
</ul>
<section id="linear-regression-for-bivariate-analysis" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="linear-regression-for-bivariate-analysis"><span class="header-section-number">6.1</span> Linear Regression for Bivariate Analysis</h2>
<section id="simple-linear-regression" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="simple-linear-regression"><span class="header-section-number">6.1.1</span> Simple Linear Regression</h3>
<p>In this chapter, we will estimate <span class="red-text">a simple linear regression model with only one independent variable</span>. In other words, we examine a bivariate relationship between a dependent variable and an independent variable using linear regression.</p>
<p>In <strong>R</strong>, we use <strong>the <code>lm()</code> function</strong> to estimate <span class="red-text">a linear regression model</span>. At minimum, <strong>the <code>lm()</code> function</strong> takes two arguments. A basic syntax of <strong>the <code>lm()</code> function</strong> in this case is as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> dependent_variable <span class="sc">~</span> independent_variable, <span class="at">data =</span> data_frame_used)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The first argument of <strong>the <code>lm()</code> function</strong> is <strong>the <code>formula</code> argument</strong>. We specify our <span class="red-text">linear regression model</span> in this argument. Suppose the model we try to estimate is given by the following formula. <span id="eq-lm1"><span class="math display">\[
  Y = \alpha + \beta X + u
\tag{6.1}\]</span></span></p>
<p>Then, we specify <strong>the <code>formula</code> argument</strong> in <strong>the <code>lm</code> function</strong> as <strong><code>formula = Y ~ X</code></strong>. That is, ignoring the coefficients, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>, we write <span class="red-text">the dependent variable <code>Y</code></span> on <strong>the left-hand side of tilde, <code>~</code></strong>, and <span class="red-text">the independent variable <code>X</code></span> on <strong>the right-hand side</strong>.</p>
<p>The second argument of <strong>the <code>lm()</code> function</strong> is <strong>the <code>data</code> argument</strong> in which we specify <span class="red-text">the name of the data frame</span> we are using.</p>
<p>Let’s estimate <span class="red-text">a linear regression</span> using the <code>usstates2010</code> data frame, in which the dependent variable is <code>ranney3_gub_prop</code> and the independent variable is <code>democrat</code>. As we saw in <a href="bivariate.html#sec-scatter" class="quarto-xref"><span>Section 5.3</span></a>, <code>democrat</code> is <span class="red-text">the percent of Democratic identifiers</span> — individuals who identify themselves as Democrats — in each state, and <code>ranney3_gub_prop</code> is <span class="red-text">the proportion of two-party vote for a democratic gubernatorial candidate</span>. We would expect <strong>a positive relationship</strong> between these two variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> ranney3_gub_prop <span class="sc">~</span> democrat, <span class="at">data =</span> usstates2010)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ranney3_gub_prop ~ democrat, data = usstates2010)

Coefficients:
(Intercept)     democrat  
   0.267577     0.006604  </code></pre>
</div>
</div>
<p>At the bottom of the output, we can see <span class="red-text">the list of coefficients estimated</span>. <strong>The number below <code>(Intercept)</code></strong> is <span class="red-text">the intercept</span> of the linear regression model. This is an estimate of <span class="math inline">\(\alpha\)</span> in the linear regression model in <a href="#eq-lm1" class="quarto-xref">Equation&nbsp;<span>6.1</span></a>. <strong>The number below <code>democrat</code></strong> is <span class="red-text">the coefficient of the <code>democrat</code> variable</span>. This is an estimate of <span class="math inline">\(\beta\)</span> in the linear regression model in <a href="#eq-lm1" class="quarto-xref">Equation&nbsp;<span>6.1</span></a>.</p>
<p>Recall that <code>ranney3_gub_prop</code> is measured in proportion, a number between 0 and 1, and <code>democrat</code> is measured in percentage, a number between 0 and 100. We can check this by <strong>the <code>summary()</code> function</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(usstates2010<span class="sc">$</span>ranney3_gub_prop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
 0.2402  0.4071  0.4708  0.4776  0.5355  0.8209       2 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(usstates2010<span class="sc">$</span>democrat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  17.73   27.39   32.52   31.79   34.37   63.20 </code></pre>
</div>
</div>
<p>It is better to measure them in the same unit. Let’s create a new variable for <span class="red-text">the two-party vote share of a democratic gubernatorial candidate measured in percentage</span>. Below I create a new variable called <code>gov_vts</code> by using <strong>the <code>mutate()</code> function</strong> and multiplying <code>ranney3_gub_prop</code> by 100.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>  usstates2010 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(usstates2010, <span class="at">gov_vts =</span> ranney3_gub_prop <span class="sc">*</span> <span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then, <span class="red-text">re-estimate the above linear regression model</span> using this new variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> gov_vts <span class="sc">~</span> democrat, <span class="at">data =</span> usstates2010)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = gov_vts ~ democrat, data = usstates2010)

Coefficients:
(Intercept)     democrat  
    26.7577       0.6604  </code></pre>
</div>
</div>
<p><strong>The coefficient on <code>democrat</code></strong> is <span class="red-text">0.66</span>. According to this model, a one percentage-point increase in the Democratic identifiers would lead to, on average, a 0.66 percentage-point increase in the two party vote share of a Democratic gubernatorial candidate.</p>
</section>
<section id="scatterplot-with-linear-regression-line" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="scatterplot-with-linear-regression-line"><span class="header-section-number">6.1.2</span> Scatterplot with Linear Regression Line</h3>
<p>In <a href="bivariate.html#sec-scatter" class="quarto-xref"><span>Section 5.3</span></a>, we drew <strong>a scatterplot</strong> of the percentage of Democratic identifiers and the Democratic gubernatorial candidate’s vote share. Let’s <span class="red-text">add a linear regression line to</span> <strong>this scatterplot</strong>.</p>
<p>First, let’s redraw <strong>the scatterplot</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( usstates2010, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>( <span class="at">x =</span> democrat, <span class="at">y =</span> gov_vts, <span class="at">label =</span> st ) ) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>( <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">col =</span> <span class="st">"blue"</span> ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simp_linreg_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p>To draw <span class="red-text">a linear regression line</span>, we add <strong>the <code>geom_smooth()</code> function</strong> <span class="red-text">with the arguments specified below</span> to our <strong>scatterplot</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( usstates2010, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>( <span class="at">x =</span> democrat, <span class="at">y =</span> gov_vts, <span class="at">label =</span> st ) ) <span class="sc">+</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>( <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">col =</span> <span class="st">"blue"</span> )  <span class="sc">+</span>  <span class="co"># Add geom_smooth() with two arguments,</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>( <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)   <span class="co">#   method = "lm" and se = FALSE.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simp_linreg_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
<p><strong>The <code>geom_smooth()</code> function</strong> draws <span class="red-text">a “smoothed” line</span> for the conditional means of <code>y</code> over the values of <code>x</code> in various methods. As we want to draw <span class="red-text">a linear regression line</span>, we should specify <strong>the <code>method</code> argument</strong> to <strong><code>lm</code></strong>, which is the function name for a linear regression model in <strong>R</strong>. If we don’t set <strong>the <code>se</code> argument</strong> to <code>FALSE</code>, <strong>the <code>geom_smooth()</code> function</strong> also draws <span class="red-text">a confidence interval</span>, which is one of the methods of statistical inference. You will learn about <span class="red-text">confidence intervals</span> later in the semester. As you haven’t learned it yet, let’s set it aside for now.</p>
<p>You can also edit <span class="red-text">the appearance of a linear regression line</span> by specifying the arguments in <strong>the <code>geom_smooth()</code> function</strong>. Below I used <strong>the <code>col</code> (or <code>color</code> or <code>colour</code>) argument</strong> to specify <span class="red-text">color of the line</span>, <strong><code>linetype</code></strong> to set <span class="red-text">type of the line</span>, and <strong><code>size</code></strong> to change <span class="red-text">line width</span>. You can find <span class="red-text">different line types</span> used in <strong>R</strong> online, for example <a href="https://r-charts.com/base-r/line-types/">here</a>. Recall that you can also look up <span class="red-text">names of colors</span> used in <strong>R</strong> online, for example, <a href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf">here</a> and <a href="https://www.nceas.ucsb.edu/sites/default/files/2020-04/colorPaletteCheatsheet.pdf">here</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( usstates2010, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>( <span class="at">x =</span> democrat, <span class="at">y =</span> gov_vts, <span class="at">label =</span> st ) ) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>( <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">col =</span> <span class="st">"blue"</span> )  <span class="sc">+</span>  </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>( <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>,    <span class="co"># Add the col, linetype, and size arguments.</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">col =</span>  <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="fl">0.5</span>)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simp_linreg_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="ordinal-categorical-variable-in-simple-linear-regression" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="ordinal-categorical-variable-in-simple-linear-regression"><span class="header-section-number">6.2</span> Ordinal Categorical Variable in Simple Linear Regression</h2>
<section id="sec-ordinal-ind-var" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-ordinal-ind-var"><span class="header-section-number">6.2.1</span> Use Ordinal Categorical Variable As Independent Variable</h3>
<p>Next we use the <code>ces2019</code> data frame and estimate <span class="red-text">a linear regression of <code>trudeau_therm_cps</code> on <code>percep_economy_cps</code></span>. Note that we say that <span class="red-text">we estimate (or fit) a linear regression of Y on X</span> or <span class="red-text">we regress Y on X</span> when <code>Y</code> is a dependent variable and <code>X</code> is an independent variable in our linear regression model.</p>
<p>Recall that <code>percep_economy_cps</code> is <strong>an ordinal categorical variable</strong>. We <span class="red-text">cannot use this variable as it is</span> in a linear regression model, because both dependent and independent variables in a linear regression model must be <strong>numbers</strong>. To estimate <span class="red-text">a linear regression of <code>trudeau_therm_cps</code> on <code>percep_economy_cps</code></span>, we first need to assign numbers to each category of <code>percep_economy_cps</code>. Since <code>percep_economy_cps</code> is an ordinal variable, it makes sense to assign numbers corresponding to the order of the categories. As <strong>an ordinal categorical variable</strong> is stored as <strong>a <code>factor</code></strong> in <strong>R</strong>, we need to <span class="red-text">transform this variable to</span> <strong>a <code>numeric</code> variable</strong>.</p>
<p>As we saw before in <a href="des2.html#sec-factor-to-numeric" class="quarto-xref"><span>Section 4.3.3</span></a>, we can <span class="red-text">transform</span> a <code>factor</code> to a <span class="red-text"><code>numeric</code></span> by <strong>the <code>as.numeric()</code> function</strong>, which preserves the order of <code>levels()</code> (= categories) assigned to a <code>factor</code> variable.</p>
<p>Let’s create <code>percep_economy_cps_n</code> as we did before.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">percep_economy_cps =</span> <span class="fu">fct_relevel</span>(percep_economy_cps, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>          <span class="st">"(2) Worse"</span>, <span class="st">"(3) About the same"</span>, <span class="st">"(1) Better"</span>) )</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">percep_economy_cps =</span> <span class="fu">fct_recode</span>(percep_economy_cps, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Worse"</span> <span class="ot">=</span> <span class="st">"(2) Worse"</span>, </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Same"</span> <span class="ot">=</span> <span class="st">"(3) About the same"</span>, </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"Better"</span> <span class="ot">=</span> <span class="st">"(1) Better"</span>) )</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, </span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">percep_economy_cps_n =</span> <span class="fu">as.numeric</span>(percep_economy_cps))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s use <strong>the <code>head()</code> function</strong> to list the values of the first few observations for <code>percep_economy_cps</code> and <code>percep_economy_cps_n</code> to check how the variable was transformed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(ces2019<span class="sc">$</span>percep_economy_cps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] Worse  Same   Better Same   Better Worse 
Levels: Worse Same Better</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(ces2019<span class="sc">$</span>percep_economy_cps_n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 2 3 2 3 1</code></pre>
</div>
</div>
<p>As you can see in these first few observations, <code>percep_economy_cps_n</code> = 1 if <code>percep_economy_cps</code> is “Worse,” <code>percep_economy_cps_n</code> = 2 if <code>percep_economy_cps</code> is “Same,” and <code>percep_economy_cps_n</code> = 3 if <code>percep_economy_cps</code> is “Better.”</p>
<p>As it is transformed into <strong>a <code>numeric</code> variable</strong> with a proper order, we <span class="red-text">can use <code>percep_economy_cps_n</code> as the independent variable</span> in our linear regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> percep_economy_cps_n, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ percep_economy_cps_n, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n  
               8.128                18.982  </code></pre>
</div>
</div>
<p>As you might have noticed, the values of <code>percep_economy_cps_n</code> are different from the numbers assigned to <code>percep_economy_cps</code> in my lecture. In the lecture, <code>-1</code>, <code>0</code>, and <code>1</code> are used, but <code>1</code>, <code>2</code>, and <code>3</code> are assigned to <code>percep_economy_cps_n</code> above. <span class="red-text">As long as consecutive numbers are assigned, the coefficient of <code>percep_economy_cps_n</code> remains the same, although the intercept will be different</span>.</p>
<p>You might have also noticed that the coefficient of <code>percep_economy_cps_n</code> produced above is slightly different from the coefficient of the perception of economy variable shown in my lecture. This is because there is a slight difference in the observations included in the analysis above and that presented in my lecture.</p>
<p>By the way, <strong>the <code>lm()</code> function</strong> can still accommodate <strong>an ordinal categorical variable</strong>, stored as <strong><code>factor</code></strong>, on <span class="red-text">the right hand side</span> of a linear regression model <span class="red-text">even without transforming it into</span> <strong>a <code>numeric</code> variable.</strong> The result, however, will be <span class="red-text">different from what’s reported above</span>. We will see this in later chapters.</p>
</section>
<section id="use-ordinal-categorical-variable-as-dependent-variable" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="use-ordinal-categorical-variable-as-dependent-variable"><span class="header-section-number">6.2.2</span> Use Ordinal Categorical Variable As Dependent Variable</h3>
<p>Now let’s consider <span class="red-text">a linear regression model of <code>satisfied_fedgovt</code> on <code>percep_economy_cps_n</code></span>. Recall that <code>satisfied_fedgovt</code> is also <strong>an ordinal categorical variable</strong>. So in this application, we use <strong>an ordinal categorical variable</strong> <span class="red-text">as the dependent variable</span> for a linear regression model. Again, we need to assign consecutive numbers to the categories of an ordinal categorical variable.</p>
<p>First, construct <strong>a <code>numeric</code> version</strong> of <code>satisfied_fedgovt</code>. Below I call this new variable <code>satisfied_fedgovt_n</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfied_fedgovt =</span> <span class="fu">fct_recode</span>(satisfied_fedgovt,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Not At All"</span> <span class="ot">=</span> <span class="st">"(4) Not satisfied at all"</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Not Very"</span> <span class="ot">=</span> <span class="st">"(3) Not very satisfied"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Fairly"</span> <span class="ot">=</span> <span class="st">"(2) Fairly satisfied"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Very"</span> <span class="ot">=</span> <span class="st">"(1) Very satisfied"</span>) )</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, </span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfied_fedgovt =</span> <span class="fu">fct_relevel</span>(satisfied_fedgovt, </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Not At All"</span>, <span class="st">"Not Very"</span>, <span class="st">"Fairly"</span>, <span class="st">"Very"</span>)) </span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">satisfied_fedgovt_n =</span> <span class="fu">as.numeric</span>(satisfied_fedgovt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s use <strong>the <code>head()</code> function</strong> to check how the variable was transformed. If you specify <span class="red-text">a number in</span> <strong>the second argument</strong> of <strong>the <code>head()</code> function</strong>, then <strong>R</strong> will display <span class="red-text">this number of observations</span> for the variable you specified. Below I set <strong>this argument</strong> to <span class="red-text">20</span>, so that <span class="red-text">the first 20 observations</span> of <code>satisfied_fedgovt</code> are displayed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>                                      <span class="co"># The second argument of the head() function specifies </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(ces2019<span class="sc">$</span>satisfied_fedgovt, <span class="dv">20</span>) <span class="co"># the number of observations to be displayed.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Fairly     Fairly     Fairly     Fairly     Not At All Not At All
 [7] Not At All Fairly     Not Very   Fairly     Not Very   Not Very  
[13] Fairly     Fairly     Very       Fairly     Fairly     Fairly    
[19] Fairly     Fairly    
Levels: Not At All Not Very Fairly Very</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(ces2019<span class="sc">$</span>satisfied_fedgovt_n, <span class="dv">20</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3 3 3 3 1 1 1 3 2 3 2 2 3 3 4 3 3 3 3 3</code></pre>
</div>
</div>
<p>As you can see above, 1 = <em>Not At All</em>, 2 = <em>Not Very</em>, 3 = <em>Fairly</em>, and 4 = <em>Very</em>. Now estimate <span class="red-text">a linear regression model of <code>satisfied_fedgovt_n</code> on <code>percep_economy_cps_n</code></span>. As we saw in lectures, linear regression is a model of <span class="red-text">the conditional means of <code>y</code></span> across the values of <code>x</code>. Since the current dependent variable is <strong>a score from 1 to 4</strong>, the conditional mean of this variable is <span class="red-text">the average score</span> given a specific value of <code>x</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> satisfied_fedgovt_n <span class="sc">~</span> percep_economy_cps_n, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = satisfied_fedgovt_n ~ percep_economy_cps_n, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n  
              1.1593                0.5753  </code></pre>
</div>
</div>
<p><strong>The coefficient on <code>percep_economy_cps_n</code></strong> is <span class="red-text">0.58</span>, which suggests that the score of satisfaction with the federal government increases, on average, by 0.58 points from <code>Worse</code> to <code>Same</code> or from <code>Same</code> to <code>Better</code> in the respondent’s perception of economy. We can also say that the satisfaction of federal government (<code>satisfied_fedgovt</code>) improves, on average, by <span class="red-text">approximately one category</span> as the respondent’s perception of economy improves from <code>Worse</code> to <code>Better</code>, because <span class="math inline">\(0.58 \times 2 = 1.16\)</span>.</p>
<p>By the way, <strong>R</strong> can still estimate a linear regression model <span class="red-text">even without transforming</span> <strong>an ordinal categorical variable</strong> from <strong><code>factor</code></strong> to <strong><code>numeric</code></strong>. Below I estimate the same model using <code>satisfied_fedgovt</code>, <strong>a <code>factor</code> version</strong> of this variable, as <span class="red-text">the dependent variable</span>. In this case, <strong>R</strong> issues a warning message, as you see below, but it quietly transforms <code>satisfied_fedgovt</code> into <strong>a <code>numeric</code> version</strong> and estimates regression coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Use satisfied_fedgovt instead of satisfied_fedgovt_n. The lm() function still </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>      <span class="co"># estimates a linear regression model but issues a warning message.</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> satisfied_fedgovt <span class="sc">~</span> percep_economy_cps_n, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in model.response(mf, "numeric"): using type = "numeric" with a factor
response will be ignored</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in Ops.factor(y, z$residuals): '-' not meaningful for factors</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = satisfied_fedgovt ~ percep_economy_cps_n, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n  
              1.1593                0.5753  </code></pre>
</div>
</div>
<p>Although <strong>R</strong> allows us to use <strong>a <code>factor</code></strong> as <span class="red-text">the dependent variable</span> for <strong>the <code>lm()</code> function</strong>, as shown above, I’d still suggest you <span class="red-text">first transform</span> <strong>a <code>factor</code></strong> <span class="red-text">to</span> <strong>a <code>numeric</code> variable</strong> and <span class="red-text">use</span> <strong>a <code>numeric</code> version</strong> of your ordinal categorical variable <span class="red-text">so that you are fully aware of what you are doing</span> — i.e., you are fully aware of using <strong>an ordinal categorical variable</strong> as <span class="red-text">your dependent variable</span>.</p>
<p>As I mentioned in my lecture, there are also <span class="red-text">advanced statistical models</span> when we use <strong>an ordinal categorical variable</strong> as <span class="red-text">our dependent variable</span>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> As such models are beyond the scope of this class, we will use <span class="red-text">a linear regression model for an ordinal categorical dependent variable</span> in this class.</p>
</section>
<section id="visualization" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="visualization"><span class="header-section-number">6.2.3</span> Visualization</h3>
<p>In <a href="bivariate.html#sec-mosaic-plot" class="quarto-xref"><span>Section 5.1</span></a>, we used <strong>a mosaic plot</strong> to visualize the relationship between <code>satisfied_fedgovt</code> and <code>percep_economy_cps</code>. With <code>satisfied_fedgovt_n</code> — <strong>the <code>numeric</code> version</strong> of <code>satisfied_fedgovt</code> — it is also possible to draw <strong>a line chart</strong> and <strong>linear regression</strong> line for these variables. Below I used only the functions which you have already learned (so the code does not come with explanations.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( <span class="fu">drop_na</span>(ces2019, percep_economy_cps), </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>( <span class="at">x =</span> percep_economy_cps, <span class="at">y =</span> satisfied_fedgovt_n, </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">group =</span> <span class="dv">1</span> ) ) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> mean, <span class="at">shape =</span> <span class="dv">17</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">"blue"</span> ) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>( <span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> mean, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>( <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>( <span class="st">"Perception of Economy"</span> ) <span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>( <span class="st">"Satisfaction with Government Score"</span> ) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>( <span class="at">ylim =</span> <span class="fu">c</span>(<span class="fl">0.75</span>, <span class="fl">4.25</span>) ) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simp_linreg_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="dummy-variable-in-simple-linear-regression" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="dummy-variable-in-simple-linear-regression"><span class="header-section-number">6.3</span> Dummy Variable in Simple Linear Regression</h2>
<section id="dummy-variable-as-logical-variable-in-r" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="dummy-variable-as-logical-variable-in-r"><span class="header-section-number">6.3.1</span> Dummy Variable As <code>Logical</code> Variable in R</h3>
<p>Recall that when we have <strong>a dichotomous variable</strong> — a variable having <span class="red-text">a dichotomous outcome</span> — we normally assign 1 to one category and 0 to the other category. Then, this variable is called <strong>a <code>dummy</code> variable</strong>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Consider <code>union</code> in the <code>ces2019</code> data frame. As you can see in the codebook for this dataset (<code>ces2019_codebook.pdf</code>), this variable records an answer to the question “Do you belong to a union?” Use <strong>the <code>table()</code> function</strong> to see its values (categories) and its relative frequency. Below I set <strong>the <code>useNA</code> argument</strong> to <span class="red-text"><code>"always"</code></span>. Then, <strong>the <code>table()</code> function</strong> also displays <span class="red-text">the number of observations with</span> <strong>a missing value (<code>NA</code>)</strong> for this variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>                                        <span class="co"># Set the useNA function to "always" to display </span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>union, <span class="at">useNA=</span><span class="st">"always"</span>)  <span class="co"># the number of observations with missing values.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
(1) Yes  (2) No    &lt;NA&gt; 
    613    2247    1161 </code></pre>
</div>
</div>
<p>As you can see, <code>union</code> is <strong>a dichotomous variable</strong>, as its outcome is either <code>Yes</code> or <code>No</code>. There are <strong>many missing values (<code>NA</code>)</strong> for this variable, because this is a response to the question asked in the post-election survey (PES) of the Canadian Election Study (CES) in 2019. There are two components in the CES 2019 survey: the first is the campaign period survey (CPS) and the second is the PES. As their names suggest, CPS was conducted during the election campaign in 2019, and PES was conducted after the election. PES includes only a subset of respondents of CPS; i.e., the number of observations is smaller in PES than in CPS.</p>
<!-- ```{r} -->
<!--   levels(ces2019$union) -->
<!-- ``` -->
<p>For <strong>a dummy variable</strong>, there is a more useful type — more precisely called <strong><code>class</code></strong> in <strong>R</strong> — of variable than <strong><code>factor</code></strong>. This variable <strong><code>class</code></strong> is called <strong><code>logical</code></strong>. <strong>A <code>logical</code> variable</strong> takes <span class="red-text">two categories</span> <strong><code>TRUE</code></strong> or <strong><code>FALSE</code></strong>, each of which corresponds to number <span class="red-text">1</span> and <span class="red-text">0</span>, respectively. If we use <strong>a <code>logical</code> variable</strong> in <strong>the <code>lm()</code> function</strong>, <strong>R</strong> will treat <code>TRUE</code> of the <code>logical</code> as <span class="red-text">1</span> and <code>FALSE</code> of the <code>logical</code> as <span class="red-text">0</span>.</p>
<p>To transform the <code>union</code> variable to <strong>a <code>logical</code></strong>, first we change the name of categories of <code>union</code> to <code>TRUE</code> and <code>FALSE</code>, and then apply <strong>the <code>as.logical()</code> function</strong> to change the variable from <code>factor</code> to <code>logical</code>. In the code below, I created a new variable — <strong>a <code>logical</code> version</strong> of <code>union</code> — called <code>union_d</code> (<code>_d</code> stands for a “d”ummy variable) in this way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019,  <span class="co"># Change the name of categories of union to TRUE and FALSE.</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">union_d =</span> <span class="fu">fct_recode</span>(union, <span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"(1) Yes"</span>, </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"(2) No"</span>) )</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019,  <span class="co"># Then, apply the as.logical() function.</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">union_d =</span> <span class="fu">as.logical</span>(union_d) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To check if <code>union_d</code> is constructed as intended, apply <strong>the <code>table()</code> function</strong> to both <code>uion</code> and <code>union_d</code> to draw <strong>a cross table</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Draw a cross table of union and union_d using the table() function.</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>union, ces2019<span class="sc">$</span>union_d, <span class="at">useNA=</span><span class="st">"always"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
          FALSE TRUE &lt;NA&gt;
  (1) Yes     0  613    0
  (2) No   2247    0    0
  &lt;NA&gt;        0    0 1161</code></pre>
</div>
</div>
<p>As you can see in the above output, all observations with <code>Yes</code> in <code>union</code> are <code>TRUE</code> in <code>union_d</code>, and those with <code>No</code> in <code>union</code> are <code>FALSE</code> in <code>union_d</code>. Therefore, <code>union_d</code> = <code>TRUE</code> if a respondent is a union member and <code>FALSE</code> otherwise.</p>
<p>Also check the <code>class</code> of <code>union</code> and <code>union_d</code> using <strong>the <code>class()</code> function</strong>. As you can see below, <code>union</code> is a <code>factor</code> but now <code>union_d</code> is a <code>logical</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class</span>(ces2019<span class="sc">$</span>union)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">class</span>(ces2019<span class="sc">$</span>union_d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "logical"</code></pre>
</div>
</div>
<!-- Also, let's check the first few observations using the `head()` function. All observations with `Yes` in `union` are `TRUE` in `union_d`, and those with `No` in `union` are `FALSE` in `union_d`. Therefore, `union_d` = `TRUE` if a respondent is a union member and `FALSE` otherwise. -->
<!-- ```{r} -->
<!--   head(ces2019$union, 10) -->
<!--   head(ces2019$union_d, 10) -->
<!-- ``` -->
</section>
<section id="use-dummy-variable-as-independent-variable" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="use-dummy-variable-as-independent-variable"><span class="header-section-number">6.3.2</span> Use Dummy Variable As Independent Variable</h3>
<p>Now we can use <code>union_d</code> — <strong>the <code>logical</code> version</strong> of <code>union</code> — as <span class="red-text">a dummy variable</span> in <strong>the <code>lm()</code> function</strong>. Below, we use <code>union_d</code> as <span class="red-text">the independent variable</span> for a linear regression of <code>trudeau_therm_cps</code>. We may expect that union members are likely to be more liberal than non-members, as Liberals have historically represented the interests of labour. Accordingly, we may expect that <code>trudueau_therm_cps</code> is, on average, higher among union members than otherwise, such that the coefficient on <code>union_d</code> is positive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> trudeau_therm_cps <span class="sc">~</span> union_d, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = trudeau_therm_cps ~ union_d, data = ces2019)

Coefficients:
(Intercept)  union_dTRUE  
     43.347        2.178  </code></pre>
</div>
</div>
<p>In the output of <strong>the <code>lm()</code> function</strong> above, the coefficient of <code>union_d</code> is displayed as <code>union_dTRUE</code>, indicating that this variable is <code>logical</code>. The coefficient is 2.18 — a positive value as we hypothesized. Since <code>uinon_d</code> takes either <code>0 = FALSE</code>, which represents a non-union member, or <code>1 = TRUE</code>, which is a union member, <span class="red-text">a one unit increase in this variable</span> is <span class="red-text">a switch from</span> <strong>a non-union member</strong> <span class="red-text">to</span> <strong>a union member</strong>. Therefore, <strong>the coefficient of <code>union_d</code></strong> represents <span class="red-text">the difference in the conditional means of the <code>trudeau_therm_cps</code></span> between <strong>the union members</strong> and <strong>non-members</strong>. That is, on average, the Trudeau thermometer is 2.18 points higher among union members than non-union members. While it is positive as we expected, the magnitude of the difference may be too small, as the range of the thermometer is from 0 to 100. In other words, there may be little or no difference in the Trudeau thermometer between union members and non-members. Later in the course, we will learn <span class="red-text">the methods for statistical inference</span> to aid us to consider if this difference is <span class="red-text">due to chance alone</span>.</p>
</section>
<section id="use-dummy-variable-as-dependent-variable" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="use-dummy-variable-as-dependent-variable"><span class="header-section-number">6.3.3</span> Use Dummy Variable As Dependent Variable</h3>
<p>Now we consider the use of <strong>a dummy variable</strong> as <span class="red-text">the dependent variable</span> in a linear regression model. Let’s fit a linear regression with <code>union_d</code> as <span class="red-text">the dependent variable</span> and <code>ideology</code> as <span class="red-text">the independent variable</span>. Since Liberals have historically represented the interests of labour unions, more liberal respondents may be more likely to be union members.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> union_d <span class="sc">~</span> ideology, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = union_d ~ ideology, data = ces2019)

Coefficients:
(Intercept)     ideology  
    0.29418     -0.01628  </code></pre>
</div>
</div>
<p>As we saw in the lecture, when we use <strong>a dummy variable</strong> for <span class="red-text">the dependent variable</span> of a linear regression, this will be a model for <span class="red-text">the probability of a dummy variable taking 1</span>. In the current context, this is a model for <span class="red-text">the probability of respondents being union members</span>. A model like this is called a <strong>Linear Probability Model</strong> or <strong>LPM</strong>.</p>
<p>In <strong>the above <code>lm</code> output</strong>, <strong>the coefficient on <code>ideology</code></strong> is <span class="math inline">\(-0.0163\)</span>, which may be interpreted as <span class="red-text">the change in probability</span> with respect to <span class="red-text">one unit increase in the independent variable</span>. Since the dependent variable takes either 0 or 1, <strong>the coefficient</strong> is <span class="red-text">the change in probability measured in the range of 0 and 1</span>. Hence, this coefficient may be interpreted that one unit increase in the ideological score would lead to <span class="red-text">the decrease in the probability of the respondents being union members</span> by <span class="red-text">0.0163</span> or <span class="red-text">1.63 percentage points</span>. Since the ideological score ranges from 0 to 10, or 11 points, the difference in the probability of being union members between the most liberal and most conservative respondents is <span class="math inline">\(0.0163 \times 10 = 0.163\)</span> or approximately 16 percentage points.</p>
<p>Below I computed the mean of <code>union_d</code> using the <code>mean()</code> function. As you see, the mean of <code>union_d</code>, which is a proportion of union members in the sample, is <span class="math inline">\(0.214\)</span>, or approximately 21%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(ces2019<span class="sc">$</span>union_d, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2143357</code></pre>
</div>
</div>
<p>This means that if we randomly draw one individual from this sample, the probability of this individual being a union member is <span class="math inline">\(0.214\)</span>, or approximately 21%. Compared to this number, the estimated difference in the probability of being union members between the most liberal and most conservative respondents (<span class="math inline">\(0.163\)</span> or approximately 16 percentage points) is a sizable difference in the probability of being union members.</p>
</section>
<section id="sec-dummy-dep-var" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="sec-dummy-dep-var"><span class="header-section-number">6.3.4</span> Dummy Dependent Variable Constructed from Nominal Categorical Variable</h3>
<p><strong>An LPM</strong> may also be used for <strong>a dummy variable</strong> created for <span class="red-text">one category of</span> <strong>a nominal categorical variable</strong>. In my lecture, I constructed <strong>a dummy variable</strong> for <span class="red-text">the vote intention for the Liberal party</span> from <strong>a nominal categorical variable</strong> of <span class="red-text">vote intention</span>. Below I create <strong>this dummy variable</strong> from <code>vote_choice_intended</code>. For this purpose, I use <strong>the <code>ifelse()</code> function</strong>, which returns a specific value based on a certain condition.</p>
<p><span class="red-text">The basic syntax</span> for <strong>the <code>ifelse()</code> function</strong> is as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(condition, value<span class="sc">-</span><span class="cf">if</span><span class="sc">-</span>true, value<span class="sc">-</span><span class="cf">if</span><span class="sc">-</span>false)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>The <code>ifelse()</code> function</strong> returns <code>value-if-true</code> specified in <strong>the second argument</strong>, <span class="red-text">if the <code>condition</code> in</span> <strong>the first argument</strong> <span class="red-text">is satisfied</span>, but it returns <code>value-if-false</code> specified in <strong>the third argument</strong> <span class="red-text">otherwise</span>.</p>
<p>We can use <strong>this <code>ifelse()</code> function</strong> to create <strong>a dummy variable</strong> for <span class="red-text">those who intended to vote for the Liberal party</span> from <strong>the nominal categorical variable</strong> <code>vote_choice_intended</code> in the following way.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                            <span class="co"># Create a new variable vote_lib using the ifelse() function.</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                    </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">vote_lib =</span> <span class="fu">ifelse</span>(vote_choice_intended <span class="sc">==</span> <span class="st">"Lib"</span>, <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>) )</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                            <span class="co"># This ifelse() function assigns "TRUE" to observations if their</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>                            <span class="co"># vote_choice_intended is "Lib" but assigns "FALSE" otherwise.</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, <span class="co"># Then, we transform vote_lib into a logical variable.</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">vote_lib =</span> <span class="fu">as.logical</span>(vote_lib) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <strong>the <code>ifelse()</code> function</strong> in the code above, <span class="red-text">the condition</span> in <strong>the first argument</strong> is specified using <strong>a double equal sign (<code>==</code>)</strong>, which is <span class="red-text">one of the logical operators</span> used in <strong>R</strong>. <span class="red-text">Logical operators</span> are used to specify <span class="red-text">a certain condition</span> to evaluate. <strong>The double equal sign (<code>==</code>)</strong> evaluates whether the left-hand side of the sign is exactly the same as the right-hand side.</p>
<p>In the code above, the condition is <code>vote_choice_intended == "Lib"</code>. This condition evaluates whether each observation of <code>vote_choice_intended</code> is <code>"Lib"</code> or not. Since <strong>the second argument</strong> of <strong>the <code>ifelse()</code> function</strong> is <code>"TRUE"</code>, <code>vote_lib</code> will be <code>"TRUE"</code> for the observations for which <code>vote_choice_intended</code> is <code>"Lib"</code>. On the other hand, <strong>the third argument</strong> of <strong>the <code>ifelse()</code> function</strong> is <code>"FALSE"</code>, so <code>vote_lib</code> will be <code>"FALSE"</code> for the observations for which <code>vote_choice_intended</code> is not <code>"Lib"</code>.</p>
<p>By the way, there are <span class="red-text">many other logical operators</span> which can be used in <strong>R</strong>. You can find them online, for example, <a href="https://www.statmethods.net/management/operators.html">here</a>.</p>
<p>Let’s check if <code>vote_lib</code> is constructed as intended by drawing <strong>a crosstab</strong> of <code>vote_lib</code> and <code>vote_choice_intended</code> using <strong>the <code>table()</code> function</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>vote_lib, ces2019<span class="sc">$</span>vote_choice_intended, <span class="at">useNA=</span><span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
          BQ  Con Greens  Lib  NDP None of these Other  PPC Will not vote
  FALSE   98  980    287    0  405            17    24   49             1
  TRUE     0    0      0  909    0             0     0    0             0
  &lt;NA&gt;     0    0      0    0    0             0     0    0             0
       
        Will spoil ballot &lt;NA&gt;
  FALSE                 9    0
  TRUE                  0    0
  &lt;NA&gt;                  0 1242</code></pre>
</div>
</div>
<p>As you see in the output above, <code>vote_lib</code> is <code>TRUE</code> for all observations for which <code>vote_choice_intended</code> is <code>Lib</code> but <code>FALSE</code> for all other observations.</p>
<!-- Let's compare the first 10 observations of `vote_choice_intended` and `vote_lib`. -->
<!-- ```{r} -->
<!--   head(ces2019$vote_choice_intended, 10) -->
<!--   head(ces2019$vote_lib, 10) -->
<!-- ``` -->
<p>Let’s use <code>vote_lib</code> as <span class="red-text">the dependent variable</span> in <strong>the <code>lm()</code> function</strong>. The independent variable is <code>percep_economy_cps_n</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(<span class="at">formula =</span> vote_lib <span class="sc">~</span> percep_economy_cps_n, <span class="at">data =</span> ces2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = vote_lib ~ percep_economy_cps_n, data = ces2019)

Coefficients:
         (Intercept)  percep_economy_cps_n  
             -0.1196                0.2380  </code></pre>
</div>
</div>
<p><strong>The coefficient on <code>percep_economy_cps_n</code></strong> is <span class="math inline">\(0.24\)</span>, which suggests that the probability of respondents voting for Liberals is higher by <span class="red-text">0.24 points</span> or <span class="red-text">24 percentage points</span> for those who perceived the state of national economy <code>Better</code> than those who perceived it <code>Same</code> or for those who perceived it <code>Same</code> than those who perceived it <code>Worse</code>. We can also say that the probability of voting for the Liberals is approximately 50 percentage points higher for those who perceived the state of economy <code>Better</code> than those who perceived it <code>Worse</code>, because <span class="math inline">\(0.24 \times 2 = 0.48\)</span>.</p>
<p>As in <strong>an ordinal categorical variable</strong>, there are also <span class="red-text">advanced statistical models</span> for <strong>a dummy dependent variable</strong>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> As such models are beyond the scope of this class, we will use <span class="red-text">a linear regression model</span> for <strong>a dummy dependent variable</strong>, or <strong>LPM</strong>, in this class.</p>
</section>
<section id="visualization-1" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="visualization-1"><span class="header-section-number">6.3.5</span> Visualization</h3>
<p>An appropriate visualization for <code>vote_lib</code> and <code>percep_economy_cps</code> may be <strong>a mosaic plot</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggmosaic) <span class="co"># Don't forget to load the ggmosaic package.</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">drop_na</span>(ces2019, percep_economy_cps, vote_lib)) <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_mosaic</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">product</span>(percep_economy_cps), <span class="at">fill =</span> vote_lib), </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightsteelblue2"</span>, <span class="st">"steelblue4"</span>)) <span class="sc">+</span></span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Vote Intention for Liberals"</span>) <span class="sc">+</span>   </span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Perception of Economy"</span>)         </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simp_linreg_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="432"></p>
</figure>
</div>
</div>
</div>
<p>It is also possible to draw <strong>a line chart</strong> with <span class="red-text">a linear regression line</span> for these variables. However, we would need to create <strong>a <code>numeric</code> version</strong> of <code>vote_lib</code> for this, because <strong>the <code>ggplot()</code> functions</strong> to draw <strong>a line chart</strong> do not accept <strong>a <code>logical</code> variable</strong> as <span class="red-text">the dependent variable</span>. Below I create <strong>a <code>numeric</code> version</strong> of <code>vote_lib</code> named <code>vote_lib_n</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>  ces2019 <span class="ot">&lt;-</span> <span class="fu">mutate</span>(ces2019, <span class="co"># Create a numeric version of vote_lib.</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">vote_lib_n =</span> <span class="fu">as.numeric</span>(vote_lib) )</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Check how the variable is constructed.</span></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>(ces2019<span class="sc">$</span>vote_lib_n, ces2019<span class="sc">$</span>vote_lib, <span class="at">useNA =</span> <span class="st">"always"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      
       FALSE TRUE &lt;NA&gt;
  0     1870    0    0
  1        0  909    0
  &lt;NA&gt;     0    0 1242</code></pre>
</div>
</div>
<p>Then, <code>vote_lib_n</code> is used to draw <strong>a line chart</strong> with <span class="red-text">a linear regression line</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>( <span class="fu">drop_na</span>(ces2019, percep_economy_cps),</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>( <span class="at">x =</span> percep_economy_cps, <span class="at">y =</span> vote_lib_n,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">group =</span> <span class="dv">1</span> ) ) <span class="sc">+</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>( <span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> mean, <span class="at">shape =</span> <span class="dv">17</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">color =</span> <span class="st">"blue"</span> ) <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>( <span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> mean, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>( <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>( <span class="st">"Perception of Economy"</span> ) <span class="sc">+</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>( <span class="st">"Probability of Voting for Liberals"</span> ) <span class="sc">+</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>( <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>) ) <span class="sc">+</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="simp_linreg_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="288"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="conditional-means-medians" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="conditional-means-medians"><span class="header-section-number">6.4</span> Conditional Means &amp; Medians</h2>
<p>If you want to compute <span class="red-text">the conditional means</span> for <strong>an ordinal categorical dependent variable</strong>, you should use <strong>a <code>numeric</code> version</strong> of this variable, because <strong>the <code>mean()</code> function</strong> does not work for <strong>a <code>factor</code></strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>ces2019 <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(percep_economy_cps) <span class="sc">%&gt;%</span>    </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Use a numerc version of an ordinal categorical dependent variable.</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>( <span class="at">cond_mean =</span> <span class="fu">mean</span>(satisfied_fedgovt_n, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  percep_economy_cps cond_mean
  &lt;fct&gt;                  &lt;dbl&gt;
1 Worse                   1.67
2 Same                    2.40
3 Better                  2.79
4 &lt;NA&gt;                    2.37</code></pre>
</div>
</div>
<p>If you want to compute <span class="red-text">the conditional means</span> for <strong>a dummy variable</strong>, however, you may still use <strong>the <code>logical</code> version</strong> of a dummy variable, because <strong>the <code>mean()</code> function</strong> also works for <strong>a <code>logical</code> variable</strong>. Recall that <strong>R</strong> interprets <code>TRUE</code> of a <code>logical</code> variable as <span class="red-text">1</span> and <code>FALSE</code> as <span class="red-text">0</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>ces2019 <span class="sc">%&gt;%</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(percep_economy_cps) <span class="sc">%&gt;%</span>      <span class="co"># You may use a logical variable.</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>( <span class="at">cond_mean =</span> <span class="fu">mean</span>(vote_lib, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  percep_economy_cps cond_mean
  &lt;fct&gt;                  &lt;dbl&gt;
1 Worse                  0.109
2 Same                   0.371
3 Better                 0.580
4 &lt;NA&gt;                   0.267</code></pre>
</div>
</div>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>These models belong to the family of models called <strong>Generalized Linear Models (GLMs)</strong>. For an ordinal categorical dependent variable, <span class="red-text"><em>an ordered logit model</em></span> or <span class="red-text"><em>an ordered probit model</em></span>, which belongs to <strong>GLMs</strong>, may be used.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>As we saw in the lecture, it may alternatively be called <strong>a <code>binary</code> or <code>indicator</code> variable</strong>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>These models also belong to the family of models called <strong>Generalized Linear Models (GLMs)</strong>. The models called <span class="red-text"><em>logit</em></span> and <span class="red-text"><em>probit</em></span> may be used for <strong>a dummy dependent variable</strong>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./bivariate.html" class="pagination-link" aria-label="Bivariate Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bivariate Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./multi_linreg.html" class="pagination-link" aria-label="Multiple Linear Regression">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple Linear Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>